praw-dev/praw

- praw/internal.py
Updated the documentation with valid values for `sort` and `time` parameters to the `_listing` method (generated by `internal._get_redditor_listing` for e.g. `Redditor.get_comment`), per [Reddit API docs](https://www.reddit.com/dev/api#GET_user_{username}_{where}), in response to [this StackOverflow question](http://stackoverflow.com/q/27768132/3001761).
> Add parameter values to docs for _listing method

- .travis.yml
[PEP478](http://legacy.python.org/dev/peps/pep-0478/) shows Python 3.5 is scheduled for beta release  on May 24, 2015 and final release on September 13, 2015. I think it's worth starting testing on Python 3.5, but allowing failures until it is at least in beta.
> Add python nightly testing

- .travis.yml
This flag has been deprecated in pip for a long time now
https://github.com/pypa/pip/pull/1098
> Remove --use-mirrors flag

- .travis.yml
This commit switches praw to the Travis Docker build system. [This blog post](http://blog.travis-ci.com/2014-12-17-faster-builds-with-container-based-infrastructure/) highlights the benefits, but the main ones are:
* Builds start in seconds
* Faster builds
* More available resources in a build container
* Better network capacity, availability and throughput
* Caching available for open source projects
* Easier to scale
> Switch to Travis Docker build system

- .travis.yml
- README.rst
Coveralls is a great tool to find out where praw needs more test coverage. If you enable the repo [on coveralls](https://coveralls.io/repos/new) this will work.
> Add coveralls

- praw/objects.py
having @restrict_access(login=True), prevents using the report function in the oauth scope.
changing the scope from None to "report" and removing the login requirement will allow the report function to work properly with Oauth.
see hide() for precedence of this change and http://www.reddit.com/dev/api/oauth#scope_report
> change scope of report()

- docs/pages/configuration_files.rst
- praw/__init__.py
- praw/handlers.py
- praw/praw.ini
- scripts/init_test_environment.py
This request stems from #318.  
I think the "target" moved slightly since this was opened.  It doesn't restore the ability to use HTTP instead of HTTPS, but a default reddit install using the install script is now HTTPS enabled using a self-signed certificate.  This allows you to ignore the certificate validation errors and successfully interact with an out of the box installation of reddit.
I did what testing I could, I wasn't familiar enough to generate new test cases for with and without valid certificates.
> Configuration options for SSL validation

- praw/__init__.py
This request adds the missing restrict access scopes to several methods, according to https://www.reddit.com/dev/api/oauth:
Method|API_PATH|Reddit Path|Scope
----|----|----|----
accept_mod_invite|accept_mod_invite|api/accept_moderator_invite|None (&#x2605;)
select_flair|select_flair|api/selectflair/|flair
get_banned|banned|r/%s/about/banned/|read
get_mod_queue|modqueue|r/%s/about/modqueue/|read
get_reports|reports|r/%s/about/reports/|read
get_spam|spam|r/%s/about/spam/|read
get_unmoderated|unmoderated|r/%s/about/unmoderated/|read
get_wiki_banned|wiki_banned|r/%s/about/wikibanned/|read
get_wiki_contributors|wiki_contributors|r/%s/about/wikicontributors/|read
(&#x2605;) The API claims it should be `modself`, but this doesn't pass the tests.
> Added missing OAuth access restriction scopes to several methods

- praw/objects.py
Because `reddit_session.user` is None when the app does not have the Identity scope, messages could not be marked as read (NoneType has no attribute mark_as_read). This method needs to work even if privatemessages is the only scope provided.
`user.mark_as_read` doesn't provide any extra functionality when you're only using a single item anyway.
&nbsp;
This is a simple PR, so I'd like this to be the last one and then I'll release 3.1.0. The to-do list is ever increasing but I've put it off long enough.
> 07 July 2015 - Remove reference to user in mark_as_read

- docs/conf.py
- docs/pages/exceptions.rst
- praw/__init__.py
- praw/decorator_helpers.py
- praw/decorators.py
- praw/objects.py
- setup.py
- tests/test_decorators.py
Utilize decorator.decorator in order to prevent method signature destruction. Using this library required flattening the existing decorator methods. It also made it such that the decorators themselves couldn't (easily) modify the docstring so we're not super DRY for that but that's okay.
Finally resolves #249.
> Fix #249 Don't destroy method signatures with decorators

- praw/__init__.py
Not just Gold members. The docstrings for `submit()` and `get_mentions()` now reflect that.
> /u/ mentions and inbox replies available to all

- praw/__init__.py
As shown in [this comment](https://www.reddit.com/r/NoStupidQuestions/comments/3dtjbs/how_do_you_stick_photos_together/) by [/u/GoldenSights](http://www.reddit.com/u/GoldenSights), this allows the params parameter within the search() function to be altered. This allows for greater use of the function, from defining pages via `params={'after' : 't3_code'}` to the option of specifically defining to use the "new" legacy search e.g. `params={'feature' : 'legacy_search'}`
> Allow search() function to use params parameter

- CHANGES.rst
- praw/objects.py
It turned out that the get_wiki_page method was not sending the oauth headers unless you had the `read` scope due to some logic within RedditContentObjects. Of course, they require the `wikiread` scope instead, so this PR reflects that. 
Visually I think this change ended up looking messy, but flake8 didn't like any of the alternatives. Hopefully my comment makes up for it.
Here's what was happening before I realized the issue: https://i.imgur.com/VbKqRcm.png
&nbsp;
I was planning to open a secondary PR that accompanies this one, but I think I accidentally just nuked it without a suitable backup, so I'm going to start rewriting that.
> fix get_wiki_page not sending the oauth headers

- docs/conf.py
This pull request causes any texinfo document made using Sphinx to carry meaningful metadata, such as category and short description.
> Give meaningful parameters for texinfo

- CHANGES.rst
- praw/helpers.py
When passing a `count` parameter, it appears reddit now always returns an
`after` parameter in the data set making for duplicate requests. The `count`
parameter has now been renamed to `uniq` for streams.
> Resolve issue #485.

- praw/helpers.py
Reason being that [deques](https://docs.python.org/2/library/collections.html#collections.deque) offer O(1) insert on *both* ends of the stack instead of just the end. Previously, using a list and appending to the 'head' is an O(n) operation.
A simple demonstration/benchmark: https://gist.github.com/eugene-eeo/549b5b5c5b72a882bc02
> Use deque instead of list

- README.rst
I missed these from my other pull request
> Remove unsupported Python versions from Readme

- praw/__init__.py
"installed app" type oauth applications don't have client secrets. For these applications, the Reddit docs specify that the secret should be passed though as an empty string.
> https://github.com/reddit/reddit/wiki/OAuth2
> The "user" is the client_id. The "password" for confidential clients is the client_secret. The "password" for non-confidential clients (installed apps) is an empty string. 
This pull request allows the oauth client_secret to remain empty by differentiating between an unset value (None) and a deliberate empty string. You can currently get around this limitation by setting the secret to some non-empty string like "placeholder", but I would rather follow the official documentation.
> OAuth password for "installed app" type

- praw/__init__.py
- praw/decorator_helpers.py
- praw/errors.py
- praw/internal.py
- praw/objects.py
- tests/test_wiki_page.py
All uses of %s and %d have been replaced with `.format`. API paths always use keywords, but miscellaneous messages are just fine with the `{0}` style.
Unfortunately, this made a lot of places feel cramped, especially the mixin methods. I decided to move a lot of the URL formatting onto their own lines instead of trying to keep a hole-in-one. 79 characters is too small for most of these :frowning: 
For two of the API paths, I had to break them into separate lines and get some parentheses involved. It looks a little funky, but it was the only way to stop flake8 from complaining about my visual indent without putting the continuation line too far to the left.
Please review thoroughly if you can. After staring at the word "format" for so long it's hard to proofread this myself.
Thanks!
&nbsp; …
> Replace all %s with .format; break up dense lines

- praw/__init__.py
I am unfamiliar with PRAWs testsuite, so apologies for not providing a testcase.
If anyone else could do that, that'd be welcome.
Here's a script to help with that and get a `"scope": "*"` response, according to the [reddit Quick Start example](https://github.com/reddit/reddit/wiki/OAuth2-Quick-Start-Example):
```py
from __future__ import unicode_literals, print_function
import praw
import six 
@praw.decorators.require_oauth
def get_bearer_access(self, username, password):
data = {'grant_type': 'password',
'username': username,
'password': password}
retval = self._handle_oauth_request(data)
#print(retval)
return {'access_token': retval['access_token'],
'scope': set(retval['scope'].split(' '))}
@property
def has_oauth_app_info(self):
return all((self.client_id is not None, …
```
> Support `*` OAuth scope (#471)

- praw/decorator_helpers.py
- praw/decorators.py
- tests/test_decorators.py
`inspect.getargspec()` is soon to be deprecated in favor of `inspect.signature()`.
`inspect.signature` was not backported for Python2, so we will keep using `inspect.getargspec()` for that.
Resolves #541
> Use inspect.signature() for Python3 and up

- praw/objects.py
- tests/cassettes/test_equality_and_hash.json
- tests/test_submission.py
Hi, I need this for tests for #554 (I'd like to be able to create sets of submissions in tests). 
Right now there is `__eq__` implemented but `__hash__` has the default implementation, which means that code like this works weird:
```
>>> s1 = list(r.get_subreddit('redditdev').get_hot())[0]
>>> s2 = list(r.get_subreddit('redditdev').get_hot())[0]
>>> s1 == s2
True
>>> hash(s1) == hash(s2)
False
```
This may cause issues for people using submissions in `set`s/`dict`s, so I think `__hash__` should be defined for consistency.
> Implement __hash__ for RedditContentObject

- tests/test_helpers_submissions_between.py
The test on travis for submissions_between is putting out debug outputs at a level of 3 and less. While great for live changes and seeing what goes wrong when making them; on travis it just kinda spams the coverage log. So; on travis; this PR makes the debug ouputs hidden.
> Hide debug ouput on travis for submissions_between

- CHANGES.rst
- praw/__init__.py
- praw/objects.py
- tests/cassettes/test_get_traffic_oauth.json
- tests/test_subreddit.py
This is a result of [this comment thread](https://www.reddit.com/r/redditdev/comments/3zfnsf/403_forbidden_on_first_praw_request_or_request/cylpuot).
This adds `get_traffic` to the UnauthenticatedReddit mixin and the Subreddit object. The endpoint is not listed on reddit's API doc page, and I couldn't determine if it's meant to be used with a particular oauth scope. The method works without any scope requirements as long as the traffic stats are public.
The endpoint returns traffic stats for days, hours, and months in the form:
`[[timestamp, uniques, pageviews, subscribers], ...]`
For now it's just returning the json dictionary. We could do something fancy with it, but I don't really think it's necessary.
> Add method get_traffic

- praw/__init__.py
- tests/cassettes/test_get_traffic_oauth.json
- tests/test_subreddit.py
In #575, I could not determine what scope was meant to be used with the `/r/subreddit/about/traffic` endpoint because it was undocumented. However, [/u/Developx](https://reddit.com/u/developx) has [shown me](https://www.reddit.com/r/redditdev/comments/3zfnsf/403_forbidden_on_first_praw_request_or_request/cyp9s2o) that `modconfig` is the correct scope for this endpoint. This PR adds the right restrict_access decorator.
The test has also been updated to use a private subreddit to prove the scope is correct.
> Add 'modconfig' scope decorator to get_traffic

- praw/__init__.py
New settings added:
- ~~`modmail_email_address`: a string for modmail forwarding~~
- ~~`modmail_email_enabled`: a boolean to enable modmail forwarding~~
- `key_color`: a 6-digit hex color (I think it's currently unused, but it's always included with a subreddit's settings and triggering an "extra settings fields" warning)
> Adds support for newer options to set_settings

- praw/__init__.py
This addresses a problem when an exception is re-thrown while using oauth.
**Problem:**
If using oauth, and the number of retries is reached, it will not re-assign the value of `self._use_oauth` before rethrowing the exception.  
In the situation where the user catches this exception, it will then cause an assertion error in the `@restrict_access` decorator from then on, such as in [this issue](https://github.com/praw-dev/praw/issues/536).
**Solution:**
Have self._use_oauth re-set for every code path.
> Fix to _use_oauth not being reset

- praw/__init__.py
Currently, the update checker will run each time a `Reddit` instance is created. This is because accessing `update_checked` with `self.` treats it as an instance variable rather than a static class variable. Changing the call to `[class name].update_checked` will treat it as a static class variable.
I haven't tested this change (so make sure to test it please), but a similar patch worked in my code base.
> Only perform the update check once per session

- CHANGES.rst
- praw/objects.py
Fixes #595.
Python2 goes looking for `__members__` and `__methods__` attributes when building the result for `dir(obj)`. These attributes are now blacklisted from RedditContentObject's `__getattr__` method which performs web requests.
> Prevent `dir` from making web requests in Python 2

- praw/objects.py
- tests/cassettes/test_distinguish_and_sticky.json
- tests/test_comments.py
Moderatable.distinguish now accepts key-word argument `sticky`.  If object is a top-level `Comment`, the `sticky` parameter is appended to the json request.  Also added a small test to ensure basic functionality works (however, I'm not sure I'm using betamax correctly).
> Sticky top-level comments.

- CHANGES.rst
- README.rst
- docs/pages/call_and_response_bot.rst
- docs/pages/comment_parsing.rst
- docs/pages/configuration_files.rst
- docs/pages/exceptions.rst
- docs/pages/oauth.rst
- docs/pages/writing_a_bot.rst
- praw/__init__.py
- setup.py
- tests/cassettes/test_submit__duplicate_url.json
- tests/test_submission.py
Email from readthedocs:
> Hello!
> Starting today, Read the Docs will start hosting projects from subdomains on
the domain readthedocs.io, instead of on readthedocs.org. This change
addresses some security concerns around site cookies while hosting user
generated data on the same domain as our dashboard.
> Changes to provide security against broader threats have been in place for a
while, however there are still a few scenarios that can only be addressed by
migrating to a separate domain.
> We implemented session hijacking detection and took precautions to limit
cookie usage, but there are still a number of scenarios utilizing XSS and
CSRF attacks that we aren't able to protect against while hosting
documentation from subdomains on the readthedocs.org domain. Moving
documentation hosting …
> Update PRAW documentation links to praw.readthedocs.io from .org.

- README.rst
`easy_install` will install the latest version regardless if it is pre-release
or not. With PRAW4 in pre-release status, it is not desirable that people
attempting to install the latest stable PRAW receive that version.
> Remove easy_install from README.rst.

- praw/__init__.py
The '*' OAuth scope provides for all possible scopes, including methods that would require 'identity'. This scope is what is used in when using the 'password' grant_type, as well as can be set manually. If using the token based flow.
> Set Reddit.user on the wildcard OAuth scope

- praw/__init__.py
Whenever the image format and the img_type are both not set to png, reddit converts the image to RGBA mode, which may be useful if the user wishes to have a png automatically converted from any given color mode to RGBA. This is also useful in the case that the optimization that matches the format causes the image to lose quality / data, which in my experience has happened to some jpegs in the past.
If a value of "jpeg" is given it is gracefully accepted and converted to "jpg", because strangely, if "jpeg" is sent to the server, given how the validator checks the value, it will default to "png".
Implemented with the "upload_as" kwarg, because this also dictates the end file type on reddit's cdn.
> Allow the user to override img_type in upload_image

- praw/decorators.py
By using filterwarnings instead of simplefilter, #367 will no longer occur
> Narrow down the DeprecationWarnings filter

- praw/__init__.py
- praw/internal.py
- setup.py
- tests/helper.py
- tests/test_internal.py
I finally looked into this after kline on the reddit-dev irc brought it up the other day.
This closes #548 and @bboe/reddit_irc#3.
The issue lies in the fact that requests does not *require* pyOpenSSL. However, if it's on the system, it injects it into urllib3 [upon loading](https://github.com/kennethreitz/requests/blob/master/requests/__init__.py#L54). This allows for certificates to be validated with SNI support.
However,  some systems, such as debian from what I recall, and others, come with pyOpenSSL 0.14 or lower. Somewhere before 0.15, a regression caused data to not be accepted as strings, albeit previously allowed. This was fixed in version 0.15 and higher.
Personally, I didn't feel that praw should outright *require* pyOpenSSL, since requests didn't. So instead, this patch …
> Resolve errors with inadequate pyOpenSSL versions

- docs/pages/faq.rst
Still an issue since the underlying prawcore uses requests and upon import SNI support is injected.
> Add faq entry on pyOpenSSL

- praw/helpers.py
The parameter is "sub", not "mod_sub", and it's unclear as to what a "valid redditor" actually is.
> Fix typo in  and clarify docs of helpers.valid_redditors

- praw/handlers.py
Fixes #636
Updates `RateLimitHandler.request` to pull in environment variables for proxies and custom SSL certificates. Necessary for PRAW to work with custom SSL certs.
> Updated RateLimitHandler request to merge environment variables

- praw/__init__.py
- tests/cassettes/test_cache_hit_callback.json
- tests/test_authenticated_reddit.py
- tests/test_handlers.py
- tests/test_oauth2_reddit.py
- tests/test_subreddit.py
- tests/test_unauthenticated_reddit.py
This feature provides tests / updates tests as mentioned in the commit summaries, and also simplifies one import in `praw.__init__` (six provides a unichar method so a if/else block is not needed for [equivalent function](https://pythonhosted.org/six/#six.unichr))
Unfortunately, one of the tests won't pass because it isn't cached and the tokens were regenerated. I've fixed this, (and found a way for it to be cached so it won't happen again) in a later commit on my /add_tests branch; however the commit history is a bit convoluted until that point and fixing conflicts is giving me a headache, so I hope that can wait until I make a PR with those commits in sequence or I can just add those commits in sequence to this PR.
> Add tests 1

- tox.ini
This patch fixes an error when running tox against the project. If these versions are not pinned, then tox encounters errors when creating the virtualenv for tests.
> Pin test dep versions for tox

- tests/cassettes/test_auto_refresh_token.json
- tests/cassettes/test_cache.json
- tests/cassettes/test_empty_captcha_file.json
- tests/cassettes/test_error_list.json
- tests/cassettes/test_inject_captcha_into_kwargs_and_raise.json
- tests/cassettes/test_limit_chars.json
- tests/cassettes/test_raise_nonspecific_apiexception.json
- tests/cassettes/test_raise_not_modified.json
- tests/cassettes/test_solve_captcha_on_bound_subreddit.json
- tests/helper.py
- tests/mock_response.py
- tests/test_authenticated_reddit.py
- tests/test_decorators.py
- tests/test_handlers.py
- tests/test_oauth2_reddit.py
This feature provides various tests and a proper fix to the auto refresh test. Additionally, some convenience methods / classes / another module is added for
* being able to avoid betamax caching too harshly by adding a dummy header value and matching against it sequentially
* tests that need the new tokens because the client ids, secrets, and refresh uris unfortunately have to match or reddit will abort the request
* Mocking a response
respectively. Sorry about being late and this being a tad longer than the previous ones.
> Add tests 3

- AUTHORS.rst
- praw/models/auth.py
Currently, the `Auth.authorize` method sets the Authorizer on the Auth instance, not the Reddit instance. This prevents Reddit.read_only from being set to False, and does not initialize a session on the Reddit instance.
> Change Auth.authorize method to set Authorizer on Reddit

- tests/conftest.py
This feature filters out access tokens from betamax cassettes. `before_record` hook is added in betamax 0.7.0.
* http://betamax.readthedocs.io/en/latest/configuring.html#filtering-sensitive-data
* https://github.com/praw-dev/praw/pull/680#discussion_r90765774
> Use before_record hook to filter out acceess tokens from cassettes.

- tests/conftest.py
Reverts praw-dev/praw#682
The PR for some reason prevents tests from successfully generating cassettes that include `DELETE` requests. Let's re-add once we have that figured out.
> Revert "Use before_record hook to filter out acceess tokens from cassettes."

- AUTHORS.rst
- CHANGES.rst
- praw/models/helpers.py
- praw/models/reddit/live.py
- tests/integration/cassettes/TestLiveThread_test_init.json
- tests/integration/cassettes/TestReddit.test_live_call.json
- tests/integration/models/reddit/test_live.py
- tests/integration/test_reddit.py
- tests/unit/models/reddit/test_live.py
This feature provides explicit interface to initialize a `praw.models.LiveThread` instance, e.g.,
```python
>>> import praw
>>> from  praw.models import LiveThread
>>> reddit = praw.Reddit(...)
>>> thread = LiveThread(reddit, 'ukaeu1ik4sw5')
>>> thread.title
u'reddit updates'
```
* nmtake/praw@e147a37
Access tokens are visible in the cassettes. I think it would be better if we could filter out those tokens with `before_record` hook.  Any thoughts?
> Add praw.models.LiveHelper.__call__

- tests/conftest.py
- tests/integration/cassettes/TestLiveThread_test_init.json
- tests/integration/cassettes/TestMultireddit.test_remove.json
- tox.ini
Fixes reverted PR #682 
This feature filters out access tokens from betamax cassettes. `before_record` hook is added in betamax 0.7.0. 
I added cassettes failed to create in #682, and some fixes (`prawtest_*` envvars are missing in test environment which is invoked from tox, ~~and pylint compliance~~ (edit: alrady solved in https://github.com/praw-dev/praw/commit/ec9b648a3668a06428f65646d7fe61408268b191).
* #682 
* http://betamax.readthedocs.io/en/latest/configuring.html#filtering-sensitive-data
* https://github.com/praw-dev/praw/pull/680#discussion_r90765774
* http://tox.readthedocs.io/en/latest/example/basic.html#passing-down-environment-variables
> Use before_record hook to filter out acceess tokens from cassettes (fixes #682)

- praw/models/reddit/subreddit.py
The `/api/site_admin` endpoint expects `exclude_banned_modqueue` to be specified while the current PRAW code sends `exclude_modqueue_banned` instead, causing the setting to always be set to false. This fixes that.
* https://www.reddit.com/dev/api/#POST_api_site_admin
> Properly update subreddit exclude_banned_modqueue setting

- AUTHORS.rst
- CHANGES.rst
- praw/models/reddit/subreddit.py
- tests/integration/cassettes/TestSubredditModeration.test_distinguish__sticky.json
- tests/integration/models/reddit/test_subreddit.py
This provides a `sticky` parameter for `SubredditModeration.distinguish()`. This allows comments to be stickied.
If the user tries to sticky a submission or a non-root comment, the parameter is ignored and the target is just distinguished. This matches the behavior of PRAW 3.
> Add sticky parameter to SubredditModeration.distinguish

- AUTHORS.rst
> Fix typo in AUTHORS.rst

- CHANGES.rst
- praw/models/reddit/live.py
- tests/integration/cassettes/TestLiveThread_test_contributor__with_manage_permission.json
- tests/integration/models/reddit/test_live.py
Fixes #710 
``live_thread.contributor()`` now returns `RedditorList` correctly. Information about pending invitations, which is included when caller have 'manage' permission,  are dropped.
> Fix LiveContributorRelationship callable return type

- CHANGES.rst
- praw/const.py
- praw/models/reddit/live.py
- tests/integration/cassettes/TestLiveThreadContribution_add.json
- tests/integration/cassettes/TestLiveThreadContribution_close.json
- tests/integration/models/reddit/test_live.py
This feature provides intaface to POST /api/live/thread/close_thread which closes the live thread permanently.
* https://www.reddit.com/dev/api#POST_api_live_{thread}_close_thread
* nmtake@e147a37#commitcomment-19895733 - API design discussion
> Add `LiveThreadContribution.close`

- CHANGES.rst
- docs/code_overview/other.rst
- docs/code_overview/other/liveupdatecontribution.rst
- praw/const.py
- praw/models/reddit/live.py
- tests/integration/cassettes/TestLiveUpdateContribution_remove.json
- tests/integration/models/reddit/test_live.py
- tests/unit/models/reddit/test_live.py
This feature provides intaface to POST /api/live/thread/delete_udpate which removes a live update.
* https://www.reddit.com/dev/api#POST_api_live_{thread}_delete_update
> Add LiveUpdateContribution.remove

- CHANGES.rst
- praw/const.py
- praw/models/reddit/live.py
- tests/integration/cassettes/TestLiveContributorRelationship_test_accept_invite.json
- tests/integration/models/reddit/test_live.py
This feature provides intaface to `POST /api/live/thread/accept_contributor_invite` which accepts an invite to contribute the live thread.
* https://www.reddit.com/dev/api#POST_api_live_{thread}_accept_contributor_invite
> Add LiveContributorRelationship.accept_invite

- CHANGES.rst
- praw/const.py
- praw/models/reddit/live.py
- tests/integration/cassettes/TestLiveUpdateContribution_strike.json
- tests/integration/models/reddit/test_live.py
This feature provides interface to `POST /api/live/:thread/strike_update` which strikes a content of live update ([example](https://www.reddit.com/live/xyu8kmjvfrww/updates/cb5fe532-dbee-11e6-9a91-0e6d74fabcc4)).
* https://www.reddit.com/dev/api#POST_api_live_{thread}_strike_update
> Add LiveUpdateContribution.strike to strike a content of a live thread.

- CHANGES.rst
- praw/const.py
- praw/models/reddit/live.py
- tests/integration/cassettes/TestLiveContributorRelationship_test_update__empty_list.json
- tests/integration/cassettes/TestLiveContributorRelationship_test_update__limited.json
- tests/integration/cassettes/TestLiveContributorRelationship_test_update__none.json
- tests/integration/models/reddit/test_live.py
This feature provides interface to `POST /api/live/:thread/set_contributor_permissions`
which updates permissions for a live thread contributor. 
* https://www.reddit.com/dev/api#POST_api_live_{thread}_set_contributor_permissions
> Add LiveContributorRelationship.update to update permissions for a live thread contributor

- CHANGES.rst
- praw/models/reddit/live.py
- tests/integration/cassettes/TestLiveContributorRelationship_test_update_invite__empty_list.json
- tests/integration/cassettes/TestLiveContributorRelationship_test_update_invite__limited.json
- tests/integration/cassettes/TestLiveContributorRelationship_test_update_invite__none.json
- tests/integration/models/reddit/test_live.py
This feature provides interface to `POST /api/live/:thread/set_contributor_permissions` with `type=liveupdate_contributor_invite` data which updates contributor invite permissions.
The difference between this `update_invite()` and `update()` is `type` data (`type=liveupdate_contributor_invite` and `type=liveupdate_contributor`, respectively). 
`ModeratorRelationship` [has same interfaces](https://github.com/praw-dev/praw/blob/7f4863b2a2dd8643adf5336287f04b3ad11e2c0e/praw/models/reddit/subreddit.py#L1349-L1398).
* https://www.reddit.com/dev/api#POST_api_live_{thread}_set_contributor_permissions
> Add LiveThreadContributorRelationship.update_invite to update contributor invite permissions

- CHANGES.rst
- praw/const.py
- praw/models/reddit/live.py
- tests/integration/cassettes/TestLiveThread_test_discussions.json
- tests/integration/models/reddit/test_live.py
This feature provides interface to `GET /live/:thread/discussions` to get submissions linking to the live thread.
* https://www.reddit.com/dev/api#GET_live_{thread}_discussions
> Add LiveThread.discussions to get submissions linking to the live thread

- CHANGES.rst
- praw/const.py
- praw/models/helpers.py
- praw/objector.py
- tests/integration/cassettes/TestReddit.test_live_now__no_featured.json
- tests/integration/test_reddit.py
- tests/unit/test_objector.py
This feature provides interface to `POST /api/live/happening_now` which gets currently featured live thread.
This commit doesn't contain test for 200 OK (the endpoint returns 200 if there is a featured live thread, 204 no content if there is no featured). So the test for latter should be added in the future.
* https://www.reddit.com/dev/api#GET_api_live_happening_now
> Add LiveHelper.now

- praw/models/reddit/live.py
- praw/objector.py
- tests/integration/models/reddit/test_live.py
Fix `LiveContributorRelationship.__call__` return type
After https://github.com/praw-dev/praw/commit/5b743ee50f81c32d5fbc4b43ce4524c028666117, the method returns RedditorList consists of normal dicts
(not Redditor instances):
```
>>> reddit.live("ukaeu1ik4sw5").contributor()
<praw.models.list.redditor.RedditorList object at 0x10c217f90>
>>> _[0]
{u'id': u't2_f3lhp', u'name': u'Acidtwist', u'permissions': [u'all']}
```
This fix changes return type to RedditorList consists of Redditor
instances. Those instances have `permissions` property:
```
>>>reddit.live("ukaeu1ik4sw5").contributor()
<praw.models.list.redditor.RedditorList object at 0x10382ef90>
>>> _[0]
Redditor(name='Acidtwist')
>>> _.permissions
[u'all']
```
> Fix LiveContributorRelationship.__call__ return type

- praw/models/reddit/submission.py
This adds documentation to `Submission.comments` showing how to use `Submission.comment_sort` and `Submission.comment_limit`. This is [already documented](http://praw.readthedocs.io/en/latest/getting_started/quick_start.html#obtain-comment-instances), but this way the information can also be found in the Code Overview as well.
I also wonder if the note in the section linked above would be helpful to include in the tutorial on [Comment Extraction and Parsing](http://praw.readthedocs.io/en/latest/tutorials/comments.html).
> Documented comment sorting and limits in Submission class

- praw/reddit.py
- tests/unit/test_reddit.py
Closes #744. When the user passes a non-None `site_name` causing `praw.Reddit(site_name)` to raise `configparser.NoSectionError`, the exception has some help text appended to it, and is reraised.
configparser.NoSectionError: No section: 'test'
You provided the name of a praw.ini configuration which does not exist.
For help with creating a Reddit instance, visit
https://praw.readthedocs.io/en/latest/code_overview/reddit_instance.html
For help on configuring PRAW, visit
https://praw.readthedocs.io/en/latest/getting_started/configuration.html
How's it look?
&nbsp;
Edit: Sorry, I'm still a noob at code coverage. I'm assuming Coveralls highlighted those lines because it wants me to write a unittest for catching that case?
Edit: All good.
> Add help message for NoSectionError

- docs/getting_started/quick_start.rst
- praw/models/reddit/submission.py
Fixes
Documentation was unclear that `replace_more()` called comments and thus it is necessary to make any changes to `comment_sort` beforehand.  
A sentence for clarification was added in two places: quickstart and submission.py
> Documents replace_more and comment_sort order

- CHANGES.rst
- docs/code_overview/other.rst
- docs/code_overview/other/modmailmessage.rst
- praw/models/reddit/modmail.py
- tests/integration/cassettes/TestModmailConversation.test_reply.json
- tests/integration/models/reddit/test_modmail.py
Partially implements #703 
This adds a `reply` method on the `ModmailConversation` class, providing the ability to reply to a modmail conversation.
The method returns a `ModmailMessage` object for the new message. However, the API actually returns a fresh copy of the conversation metadata and all the messages (or is it just a subset?). This data could be used to do something more fancy, but for now I went with the simpler option.
> Add ModmailConversation.reply

- praw/models/inbox.py
`unread(mark_read=True)` does not mark each message, just the inbox.  
https://www.reddit.com/r/redditdev/comments/3502mg/_/cqzu3wz/
> update inbox.unread() docs to reflect actual behavior

- CHANGES.rst
- praw/const.py
- praw/models/reddit/modmail.py
- praw/models/reddit/subreddit.py
- tests/integration/cassettes/TestSubredditModmail.test_conversations.json
- tests/integration/cassettes/TestSubredditModmail.test_conversations__other_subreddits.json
- tests/integration/cassettes/TestSubredditModmail.test_conversations__params.json
- tests/integration/models/reddit/test_subreddit.py
Partially implements #703 
Some notes:
Working on this feature has me wondering if `ModmailConversation.__call__` has the right name. Compare with `SubredditRelationship`, where `__call__` is a listing and individual relationships are handled through named methods.
There is a `limit` parameter. However, I wasn't able to find any maximum: in manual testing, I got as far as 1998 before I ran out of conversations to request. For this reason, I didn't make use of the existing `ListingGenerator` framework.
The second commit returns a list of `ModmailConversation` objects with just the `id` and no other data. The last commit adds some parsing: the idea is to just use the conversation metadata, while leaving messages and mod actions to be fetched on the individual conversation. This required a …
> Add support for fetching modmail conversation lists

- docs/examples/obtain_refresh_token.py
- docs/getting_started/configuration/options.rst
- docs/getting_started/configuration/prawini.rst
- docs/getting_started/quick_start.rst
- docs/package_info/contributing.rst
- praw/models/inbox.py
- praw/models/listing/mixins/subreddit.py
- praw/models/reddit/base.py
- praw/models/reddit/mixins/__init__.py
- praw/models/reddit/modmail.py
- praw/models/reddit/more.py
- praw/models/reddit/subreddit.py
- praw/reddit.py
- tests/integration/models/test_comment_forest.py
- tests/unit/models/reddit/test_subreddit.py
Found I typo I added, tried to find others. The only real code change is [`Subreddit.subscribe`](https://github.com/praw-dev/praw/compare/master...elnuno:typos?expand=1#diff-a6c46ac5ed8df35e279b7cd7973765fcL483), but I'm assuming it's a fix too (inital -> initial):
```python
data = {'action': 'sub', 'skip_inital_defaults': True,
'sr_name': self._subreddit_list(self, other_subreddits)}
```
> Fix some typos.

- tests/conftest.py
Fixes #787 
I was unsure how to test whether this actually works. Perhaps delete and re-record some cassette with an affected password?
> URL-escape password placeholder for Betamax

- docs/conf.py
- docs/docutils.conf
Sphinx has deprecated the `html_use_smartypants` option, resulting in [a bunch of noise](https://travis-ci.org/praw-dev/praw/jobs/244599349#L697) when running the pre-push scripts. This PR moves this option  to docutils config as described at rtfd/readthedocs.org#2940.
> Replace deprecated Sphinx option "html_use_smartypants"

- CHANGES.rst
- docs/code_overview/other.rst
- docs/code_overview/other/subredditlinkflairtemplates.rst
- docs/code_overview/other/subredditredditorflairtemplates.rst
- praw/const.py
- praw/models/reddit/subreddit.py
- tests/integration/cassettes/TestSubredditLinkFlairTemplates.test__iter.json
- tests/integration/cassettes/TestSubredditLinkFlairTemplates.test_add.json
- tests/integration/cassettes/TestSubredditLinkFlairTemplates.test_clear.json
- tests/integration/models/reddit/test_subreddit.py
Fixes #812.
I tried a couple different approaches to getting rid of the `is_link` parameters. I wanted to keep it around since existing code might do something like:
subreddit.flair.templates.clear(is_link=True)
The latest commit removes a lot of code duplication, and it seemed to me like the best approach.
> Support link_flair endpoint

- setup.py
This will enable prawdditions (and any other PRAW clients) to use the new `prawcore.exceptions.Conflict`.
> Depend on prawcore >= 0.11.0, <0.12.0

- tests/conftest.py
Fixes issues with #788 
This fixes the password problems I had in my previous pull request (#835).
My password contains two symbols: a `*` and a `!`, however my password was showing up in the cassettes JSON files with the two symbols encoded as `%252A` and `%2521` respectively rather than `%2A` and `%21`. This would mean that the password is getting URL-encoded twice.
So my guess is that Betamax is already automatically doing URL-encoding, so I removed the `placeholders['password'] = quote_plus(placeholders['password'])` line. And then I set it so that `password` is URL-encoded only when being passed into `define_cassette_placeholder`.
This worked for me. Can anyone else confirm?
Mentioning @leviroth
> Fixes URL-escape password placeholder for Betamax

- AUTHORS.rst
- CHANGES.rst
- praw/models/reddit/submission.py
- praw/models/reddit/subreddit.py
- tests/integration/cassettes/TestSubmission.test_crosspost.json
- tests/integration/cassettes/TestSubmission.test_crosspost__custom_title.json
- tests/integration/cassettes/TestSubmission.test_crosspost__subreddit_object.json
- tests/integration/models/reddit/test_submission.py
Fixes n/a
This feature provides support for creating a crosspost. Today (4/24/2017) Reddit [launched the beta for crossposting](https://www.reddit.com/r/modnews/comments/6vths0/beta_crossposting_better_attribution_for_cat/). As the beta launched just today, things could still change so I've marked this pull request as WIP in case of Reddit crosspost API changes between now and when the beta ends.
I have the crosspost method take a thing `fullname` instead of an `id` because Reddit plans to add support for crossposting comments some time in the future.
Maybe it would be better to have the `crosspost` method be on the Submission class and take the subreddit to crosspost to as the parameter?
I can confirm this works:
```
$ py
Python 3.6.0 (v3.6.0:41df79263a11, Dec 23 2016, 07:18:10) [MSC …
```
> [WIP] Add crosspost support

- praw/exceptions.py
- tests/unit/test_exceptions.py
- tox.ini
Fixes #845
Now APIException's error message string is escaped with `unicode_escape`.
```
$ python2
Python 2.7.13 (default, Jul 18 2017, 09:16:53)
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from praw.exceptions import APIException
>>> ex = APIException('RATELIMIT', u'実行回数が多すぎます', u フィールド')
>>> str(ex)
"RATELIMIT: '\\u5b9f\\u884c\\u56de\\u6570\\u304c\\u591a\\u3059\\u304e\\u307e\\u3059' on field '\\u30d5\\u30a3\\u30fc\\u30eb\\u30c9'"
>>> ex.message
u'\u5b9f\u884c\u56de\u6570\u304c\u591a\u3059\u304e\u307e\u3059'
$ python3
Python 3.6.2 (default, Jul 17 2017, 16:44:47)
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)] on darwin
Type "help", "copyright", "credits" or "license" for more …
```
> Escape API Exception message with `unicode_escape` encoding

- praw/exceptions.py
Re #846
* `.. note:` -> `.. note::` to prevent the `note` from being interpreted as a comment, which wouldn't show up when the docs are rendered.
* Double backticks for the code bits.
* Correct typo ("atribute" -> "attribute").
* Sphinx doesn't like characters immediately after the backticks, so add a hyphen in to prevent it from being rendered incorrectly.
N/A
> Fix a few Sphinx typos

- praw/models/reddit/subreddit.py
Fixes #848
This feature provides clarification in the documentation that subreddit filtering (`reddit.subreddit('all-the_donald')`) does not work for some methods, including methods for returning comments.
* [/r/redditdev thread](https://www.reddit.com/r/redditdev/comments/6yhalr/cant_block_subreddits_with_praw/)
> Clarify subreddit filtering

- praw/models/reddit/subreddit.py
This adds an example and a note saying that "contributor" is another term for "approved submitter."
Reddit's API and associated documentation use the term "contributor" where the website uses the term "approved submitter." PRAW currently follows the API documentation only, which makes it hard to find things by searching for "approved submitter."
* https://www.reddit.com/r/redditdev/comments/72v97e/praw_invite_user_to_inviteonly_subreddit/
> Document that "contributor" is another term for "approved submitter"

- CHANGES.rst
- praw/const.py
- praw/models/reddit/live.py
- pre_push.py
- tests/integration/cassettes/TestLiveUpdate_test_attributes.json
- tests/integration/models/reddit/test_live.py
- tests/unit/models/reddit/test_live.py
- tox.ini
This feature provides lazy attribute population on LiveUpdate instance. E.g.,
```
>>> from praw.models import LiveUpdate
>>> import praw
>>> reddit = praw.Reddit(...)
>>> update = LiveUpdate(reddit, 'ukaeu1ik4sw5', '7827987a-c998-11e4-a0b9-22000b6a88d2')
>>> update.author
Redditor(name='umbrae')
```
Until now, a LiveUpdate instance hadn't been able to get details from reddit
when a attribute is first accessed because of the reddit API's limitation.
But [the limitation is recently removed](https://github.com/reddit/reddit-plugin-liveupdate/commit/88a490f733bf9c889005b39f9569ce6cd094f445), so this commit reflects the change.
> Make Liveupdate attributes lazy

- docs/code_overview/models/comment.rst
- docs/getting_started/quick_start.rst
While getting to know PRAW, I was wondering about existing attributes of a `Submission` object which were not listed in the docs under [Working with PRAW’s Models » Submission](https://praw.readthedocs.io/en/latest/code_overview/models/submission.html). So I posted [a question](https://stackoverflow.com/questions/46840319/why-is-submission-permalink-with-praw-working-even-if-i-cant-find-anything) about it on Stack Overflow. Turns out, while intensely studying the Model's page, I simply missed [this section](https://praw.readthedocs.io/en/latest/getting_started/quick_start.html#determine-available-attributes-of-an-object) from the Quick Start docs about dynamically provided attributes. Therefore, I think it might be a good idea to add a note at the bottom of each Model's list of attributes …
> Point out dynamically provided attributes

- docs/getting_started/authentication.rst
This adds documentation concerning how to use/why not to use 2FA with script auth.
Fixes #863.
> Add documentation for 2FA

- CHANGES.rst
- praw/const.py
- praw/models/reddit/mixins/inboxable.py
- praw/models/reddit/redditor.py
- tests/integration/cassettes/TestRedditor.test_block.json
- tests/integration/models/reddit/test_redditor.py
This feature provides support for the API endpoint /api/block_user, which I believe is fairly new. Specifically, it adds the `Redditor.block()` method, which accepts no params and blocks the Redditor it belongs to.
* https://www.reddit.com/dev/api/#POST_api_block_user
> Add Redditor.block()

- docs/tutorials/comments.rst
Hi! Long time no commit.
The last few code snippets on the "Comment Extraction and Parsing" page use a `limit` of 0, but I believe they were supposed to say `None` because it sounds like they're supposed to fetch all comments.
I clarified the meaning of `limit=0` vs `limit=None`, and changed the limits in the last snippets to `None` especially because these are the most frequently copy-pasted.
Admittedly the one that only prints toplevel comments is kind of wasteful to fetch all the Mores, but since we don't have a root-only version I feel it's the better of the two and, again, people are going to be copying this.
There's a new section header just for this `replace_more` lesson because I think the topic is big enough to deserve it.
* …
> Clarify usage of `limit` in the `replace_more` tutorial.

- docs/code_overview/models/comment.rst
- docs/code_overview/models/livethread.rst
- docs/code_overview/models/liveupdate.rst
- docs/code_overview/models/message.rst
- docs/code_overview/models/modmailconversation.rst
- docs/code_overview/models/more.rst
- docs/code_overview/models/multireddit.rst
- docs/code_overview/models/note_dynamically_provided_attributes.txt
- docs/code_overview/models/redditor.rst
- docs/code_overview/models/submission.rst
- docs/code_overview/models/subreddit.rst
- docs/code_overview/models/wikipage.rst
- docs/code_overview/praw_models.rst
This new pull request is about the first point on my list in #862 which seems to have been overlooked:
> * For now, this pull request consists only of changes made to `comment.rst`. However, if you like my suggestion, of course the note should be appended to each file in `docs/code_overview/models/`.
I'm sorry, I only now found time to have a look at my previous pull request again and saw that it's been merged already. What did I do wrong? Maybe I should have put a certain label on the pull request? I'm sorry for the inconvenience.
So this is a new pull request to add the note about dynamically provided attributes to all Models - not only to `comment.rst`. My commits for this pull request do
* add a substitution definition (which contains the content of the previously already added note …
> Add note about dynamically provided attributes to all Models

- CHANGES.rst
- praw/models/reddit/submission.py
- tests/unit/models/reddit/test_submission.py
Currently, a line like `s = reddit.submission(url='https://redd.it/2gmzqe/')` will raise `ClientException: Invalid URL: https://redd.it/2gmzqe/`. This is due to the way URLs are parsed: if a URL doesn't have the 'comments' component, it only parses properly if there is no trailing slash. 
This PR adds a test case that should pass but fails, and then fixes the issue.
> Parse short URLs with trailing slashes

- praw/reddit.py
The docstring previously retained information on the `param_list` parameter, which has since been split into `fullnames` and `url`.
> Update Reddit.info docstring for new parameters

- praw/models/reddit/submission.py
- tests/unit/models/reddit/test_submission.py
Fixes https://github.com/praw-dev/praw/issues/885#issuecomment-359636839 (bboe's note in the linked comment)
This feature provides more robust parsing of URLs for submissions. Specifically, it attempts to deny subreddit links such as https://reddit.com/r/wallpapers from being turned into submission objects. This is probably an area that can be improved further in the future.
> Further improve URL parsing for submissions

- CHANGES.rst
- docs/code_overview/other.rst
- docs/code_overview/other/preferences.rst
- praw/const.py
- praw/models/__init__.py
- praw/models/preferences.py
- praw/models/user.py
- praw/reddit.py
- tests/integration/cassettes/TestPreferences.test_update.json
- tests/integration/cassettes/TestPreferences.test_view.json
- tests/integration/models/test_preferences.py
This feature provides an interface to view and update Reddit preferences. Usage is intended to be as follows:
```python
prefs = reddit.user.preferences()  # view
print(prefs['show_link_flair'])
reddit.user.preferences.update(show_link_flair=True)  # update
```
Preferences are returned as a dict by a call to `reddit.user.preferences()` and can be updated with the `reddit.user.preferences.update()` method, with keyword-argument names being the preference names, and the values being the values. Preferences that have names that would be illegal keyword-argument names in Python (there are three at present) can still be updated like so:
```python
reddit.user.preferences.update(**{'3rd_party_data_personalized_ads': False})
```
I documented the keyword-arguments as best I can, but some of them …
> Add support for interfacing with Reddit preferences

- AUTHORS.rst
I added myself to the "Team Members" section with a name and email. I used last initials instead of the full name for privacy (hope that's okay).
> Move myself up to "Team Members" and add name and email

- praw/models/reddit/wikipage.py
I was trying to grab the content from an old WikiPage revision last night and it was a bit tricky to see that the `WikiPage` object was mapped from the `'page'` key. This doc update tries to make this more clear.
> Add example for getting WikiPage instance from a revision

- praw/models/reddit/emoji.py
- tests/unit/models/reddit/test_emoji.py
Fixes #909
This feature provides a `__repr__` for the `SubredditEmoji` class. It does not provide a `__str__` because I don't believe a meaningful string representation of `SubredditEmoji` exists. 
It also removes `SubredditEmoji`'s inheritance from `RedditBase`. I think this is an appropriate change because `SubredditEmoji` doesn't implement the necessary structure to support [`_fetch()`](https://github.com/praw-dev/praw/blob/5a8a4aff155b1314cbf0f893425e8379a007d4ca/praw/models/reddit/base.py#L70-L84), so something like `reddit.subreddit('redditdev').emoji.unknown_attr` also raises a `RecursionError`.
> Fix SubredditEmoji repr

- praw/models/util.py
The examples on `stream_generator` show how to use various functions that themselves use `stream_generator`, and thus they show how to use the `pause_after` parameter. However, there isn't an example showing how to call `stream_generator` itself, given some listing function. This PR adds such an example.
The `reply_function` name is a little weird but the line got too long otherwise.
> Add example showing usage of stream_generator

- docs/_static/theme_overrides.css
- docs/conf.py
- praw/models/reddit/subreddit.py
In connection with #917. (but this PR and its commits are not meant to close that issue)
I documented common attributes for the Subreddit class. This is intended to be used as a sample/model for others who wish to get involved with PRAW and want to add more of these as a first contribution.
756edc313e45f34933c86835eb989b90618400cd adds a CSS modification to the built doc pages that ensures table cells can wrap their text. Without it, all table cells are displayed as one long horizontally-scrollable line of text. **A potential problem with this commit is that I directly copied and pasted the CSS and Python configuration from [this link](https://rackerlabs.github.io/docs-rackspace/tools/rtd-tables.html)**. I strongly suspect there is a copyright or licensing issue here, but I don't know how …
> Document common Subreddit attributes

- .github/ISSUE_TEMPLATE.md
Uses a bulleted list for each item in the "System Information" section.
This prevents "PRAW Version" from appearing as a code block and makes each item render on a separate line.
> Use bulleted list for "System Information" section

- docs/getting_started/configuration.rst
Fixes #934
Added a section on how to configure and pass in a custom Session when instantiating the Reddit class, with an example based on #934. 
I'm not entirely happy with how this is written, so I'm definitely open to suggestions.
* https://stackoverflow.com/a/50160417/3357935
* #934 
* http://docs.python-requests.org/en/master/user/advanced/#ssl-cert-verification
> Document configuring a custom requests Session

- praw/models/reddit/modmail.py
- praw/models/reddit/subreddit.py
A mistake in the docstring of `Modmail.conversations` used `reddit.subreddit('all').conversations(state='mod')` where it should have used `reddit.subreddit('all').modmail.conversations(state='mod')`. This PR fixes that.
In addition, many of the code samples are forced to line-wrap sooner than is ideal because of indentation eating into the line-width cap. This PR fixes this by escaping the newlines and unindenting the following lines where this occurs so that the documentation will render code in just one line where appropriate. This fix required disabling two pydocstyle rules for each docstring where it was applied.
As an example of the fix, code currently rendered in documentation as
```python
conversation = reddit.subreddit('redditdev').modmail('2gmz',
mark_read=True)
```
becomes …
> Improve Modmail and ModmailConversation documentation style

- CHANGES.rst
- praw/models/auth.py
- praw/reddit.py
- tests/unit/models/test_auth.py
- tests/unit/test_reddit.py
Fixes #955
This commit allow users to use OAuth2 code flow (which exchanges an authorization code 
for an access token and optional refresh token) from installed apps.
Unfortunately, this commit doesn't have proper integration test for `authorize()`,
because tests in integration/models/test_{comment_forest,inbox,more}.py
doesn't work for installed apps. Those tests use 
`match_requests_on=['uri', 'method', 'body']`, so new cassette is required
if installed apps credentials are given. 
* https://github.com/reddit-archive/reddit/wiki/OAuth2#retrieving-the-access-token
> Allow installed apps to use OAuth2 code flow

- .pylintrc
Fixes #964 
This PR also disables [no-else-return](http://pylint.pycqa.org/en/latest/technical_reference/features.html?highlight=no-else-return
). If the directive is active, pylint emits following messages:
```
$ pylint praw
************* Module praw.objector
R1705: 123, 8: Unnecessary "elif" after "return" (no-else-return)
************* Module praw.models.auth
R1705: 111, 8: Unnecessary "elif" after "return" (no-else-return)
************* Module praw.models.helpers
R1705: 159, 8: Unnecessary "elif" after "return" (no-else-return)
```
I think this directive is too much. If it should be enabled, I'll follow that.
> Disalbe pylint's useless-object-inheritance and no-else-return in .pylintrc

- praw/models/reddit/redditor.py
Not 100% sure how I should list the items in the `subreddit` dictionary (if at all). Currently listed them as how they would be accessed, but maybe a separate table would be a bit neater?
> Added typical attributes for Redditor model

- praw/models/reddit/submission.py
N/A
The attribute returned by Reddit denoting NSFW posts is called `over_18` instead of `over18`.
I couldn't find the submission API endpoint in the Reddit API docs but every other usage of the term includes the underscore. It can also be tested by checking the attributes of a submission object i.e. `print(vars(submission_object))`.
> Submission model docs - changed over18 to over_18

- praw/models/util.py
Adds a key_name parameter to the stream_generator function so it can key off things other than "fullname".
Per: https://old.reddit.com/r/redditdev/comments/9mb0m9/praw_submodlog_stream_generator_throws/
> Add key_name param to stream generator

- praw/models/reddit/subreddit.py
There's a question every other week in /r/redditdev about how to skip existing comments in a stream since people don't know to check the streamgenerator docs.
> Add an example of the skip_existing argument to the comment stream docs

- CHANGES.rst
- docs/code_overview/other.rst
- docs/code_overview/other/subredditwidgetsmoderation.rst
- docs/code_overview/other/widgetmoderation.rst
- praw/models/__init__.py
- praw/models/reddit/widgets.py
- praw/reddit.py
- tests/integration/cassettes/TestTextArea.test_create.json
- tests/integration/models/reddit/test_widgets.py
- tests/unit/models/reddit/test_widgets.py
This feature provides the `WidgetModeration` class to moderate a particular widget and the `SubredditWidgetsModeration` class to moderate a subreddit's widgets. The former class is used to perform actions on a specific widget, for example, to delete it with `widget.mod.delete()`. The latter is used to perform actions on a subreddit's widgets as a whole, such as (not implemented in this PR) reordering them, or creating them (`widgets.mod.add_text_area()`).
The `SubredditWidgetsModeration` class provides a private helper method for creating widgets, as well as a method to create `TextArea` widgets. More will come in later PRs. In addition, it will support re-ordering widgets.
The `WidgetModeration` class provides `update` and `delete` methods for all `Widget`s.
- Added a …
> Add WidgetModeration and SubredditWidgetsModeration

- CHANGES.rst
- praw/models/reddit/widgets.py
- tests/integration/cassettes/TestSubredditWidgetsModeration.test_reorder.json
- tests/integration/models/reddit/test_widgets.py
This feature provides the ability to re-order widgets in a subreddit's sidebar through the `reorder()` method. 
Note: This PR should be merged after #993. Some of the commits in this PR are supposed to be merged in that commit, but since it hasn't been merged yet and this branch is based on that branch, they show up as part of this PR.
> Support reordering widgets

- AUTHORS.rst
- praw/const.py
- praw/models/reddit/comment.py
- praw/models/reddit/mixins/__init__.py
- praw/models/reddit/submission.py
- praw/objector.py
- tests/integration/cassettes/TestCommentModeration.test_send_removal_message.json
- tests/integration/cassettes/TestSubmissionModeration.test_send_removal_message.json
- tests/integration/models/reddit/test_comment.py
- tests/integration/models/reddit/test_submission.py
- tests/unit/models/reddit/mixins/test__init__.py
Adds support for the removal message endpoints: `removal_link_message` and `removal_comment_message`.
This is part of #976 rebased.
> Removal Messages support

- docs/_static/theme_override.css
- docs/getting_started/authentication.rst
- docs/getting_started/configuration.rst
Fixes #983
This feature provides better documentation for OAuth2 flows based around the flow type, rather than the application type.
Note I have commited documentation on how to switch between these flows yet, because currently the only way (for a script app, and for read-only modes) is to change private attributes, and I think that should be discussed first (I don't know what the policy on that is here). If that discussion leads to "leave as is" I'll push a commit adding said documentation.
I also haven't added documentation regarding the importance of checking the `state` string after a given redirect, because while currently ambiguous it's out of the scope of this PR (however I can add it if wanted).
* https://github.com/reddit-archive/reddit/ (source code)
* …
> Update documentation to inform on all OAuth2 flows

- praw/models/reddit/emoji.py
- praw/models/stylesheet.py
- praw/models/trophy.py
See #917.
This feature provides attribute documentation for the `Emoji`, `Stylesheet`, and `Trophy` classes.
The issue says 
> please make a pull request for each model at a time, rather than attempting to complete for all models at once
but I figured it might be alright for three small commits to be together in one PR. I can split it up if need be.
* #917
> Document known attributes on Emoji, Stylesheet, and Trophy

- praw/models/reddit/live.py
- praw/models/reddit/multi.py
- praw/models/reddit/wikipage.py
See #917.
This feature provides attribute documentation for the `LiveThread`, `LiveUpdate`, `Multireddit`, and `WikiPage` classes.
As with #1008, the issue says 
> please make a pull request for each model at a time, rather than attempting to complete for all models at once
but I figured it might be alright for three small commits to be together in one PR. I can split it up if need be.
* #917
> Document known attributes on LiveThread, LiveUpdate, Multireddit, and WikiPage

- AUTHORS.rst
- CHANGES.rst
- praw/models/reddit/subreddit.py
- tests/integration/cassettes/TestSubreddit.test_submit__nsfw.json
- tests/integration/models/reddit/test_subreddit.py
The Reddit API has the parameter `nsfw` in /api/submit, which immediately marks the submission as NSFW. However, PRAW currently requires you to call `Submission.nsfw`, which works via the `/api/marknsfw` endpoint. This requires the `modposts` scope. This pull request adds the parameter to the `submit`, `submit_image`, and `submit_video` methods via a new keyword argument.
P.S. Another good addition might be the spoiler parameter, which is basically the same situation.
* https://www.reddit.com/dev/api/oauth#POST_api_submit
* https://www.reddit.com/dev/api/oauth#POST_api_marknsfw
> Add the ability to immediately mark submissions as NSFW

- CHANGES.rst
- praw/models/reddit/subreddit.py
- tests/integration/cassettes/TestSubreddit.test_submit__spoiler.json
- tests/integration/models/reddit/test_subreddit.py
This feature makes the `spoiler` param of the `/api/submit` method on the Reddit API available through PRAW's `Subreddit.submit()` method. This basically does the same thing for `spoiler` as https://github.com/praw-dev/praw/pull/1030 did for `nsfw`.
* https://www.reddit.com/dev/api/#POST_api_submit
> Add the ability to immediately mark submissions as spoilers

- CHANGES.rst
- praw/models/reddit/subreddit.py
Fixes #1028
This feature provides a higher default websocket timeout in the image and video submission methods, and allows it to be customized.
I chose 10 as the new default because it should allow most images to be submitted without timeout. Some very large images, such as the example in #1028, will still require manually higher timeout values. The downside is that, when there are errors, code may essentially hang for 10 seconds.
I also [removed the timeout of 2](https://github.com/praw-dev/praw/commit/16ae17d3eb77673f25f5b17cd6ed76615a3b352b#diff-a6c46ac5ed8df35e279b7cd7973765fcR453) from the `socket.close()` call. It will use the default websocket client value, [which is 3](https://github.com/websocket-client/websocket-client/blob/66081be8e0523c9dfaffcb18ba1c8e4765e2288e/websocket/_core …
> Raise and customize timeout when submitting images and videos

- praw/models/reddit/base.py
- praw/models/reddit/comment.py
- praw/models/reddit/live.py
- praw/models/reddit/message.py
- praw/models/reddit/mixins/__init__.py
- praw/models/reddit/mixins/fullname.py
- praw/models/reddit/redditor.py
- praw/models/reddit/submission.py
- praw/models/reddit/subreddit.py
This feature separates out behaviors related to `fullname` from `RedditBase`, because there are many objects which benefit from the `RedditBase` model but do not have fullnames.
This PR is related to [conversation](https://github.com/praw-dev/praw/issues/1053#issuecomment-487463864) in #1053 about proper inheritance.
All tests pass without modification; all code is formatted by `black`.
@Pyprohly said:
> Hey, what about `AttributeMixins.Fullname`? Define a whole namespace for attribute mixins.
>
> `fullname` is the only custom attribute on PRAW objects at the moment, but it might be useful to add more to `AttributeMixins` in future.
I think this is worth exploring, but we should consider this once we have other custom attributes to put in the namespace.
> Add FullnameMixin to separate fullname functionality from RedditBase

- praw/models/reddit/collections.py
This PR fixes two minor issues with the Collections PR:
- Don't index into the `string_types` tuple
- Use `Reddit.config` to get submission kind rather than `Objector.kind`
* https://github.com/praw-dev/praw/pull/1069#discussion_r283130101
> Fix issues with #1067

- AUTHORS.rst
- praw/models/reddit/mixins/__init__.py
- praw/models/reddit/submission.py
- tests/integration/models/reddit/test_comment.py
Hi,
by moving the `lock` and `unlock` methods from Submission to ThingModerationMixin, they are available also to Comment objects.
I've added the test cases, but I'm not providing a cassette, you can easly generate one by running `pytest`.
The methods are tested anyway, on my test subreddit.
Fixes #1073
This feature provides lock and unlock methods for 
* https://www.reddit.com/r/modnews/comments/brgr8i/moderators_you_may_now_lock_individual_comments/
> Add lock and unlock to Comments

- praw/models/front.py
- praw/models/listing/domain.py
- praw/models/listing/generator.py
- praw/models/listing/listing.py
- praw/models/listing/mixins/redditor.py
- praw/models/listing/mixins/subreddit.py
- praw/models/reddit/base.py
- praw/models/reddit/collections.py
- praw/models/reddit/comment.py
- praw/models/reddit/live.py
- praw/models/reddit/mixins/fullname.py
- praw/models/reddit/modmail.py
- praw/models/reddit/multi.py
- praw/models/reddit/redditor.py
- praw/models/reddit/submission.py
- praw/models/reddit/subreddit.py
- praw/models/reddit/wikipage.py
- praw/models/user.py
- praw/objector.py
- tests/integration/models/reddit/test_comment.py
- tests/unit/test_objector.py
By taking advantage of assumptions when targeting endpoints, we can often skip having to go though the Objector to identify the fetched data and jump straight to instantiating it.
> Have models be more independent from the Objector

- CHANGES.rst
- praw/models/listing/mixins/subreddit.py
- praw/models/reddit/comment.py
- praw/models/reddit/live.py
- praw/models/reddit/message.py
- praw/models/reddit/mixins/fullname.py
- praw/models/reddit/redditor.py
- praw/models/reddit/submission.py
- praw/models/reddit/subreddit.py
- tests/integration/models/reddit/test_subreddit.py
The value of `.kind` is an implementation detail of the API.
Prefer `comment is Comment` instead of `comment.kind == "t1"`.
> Remove `FullnameMixin.kind`

- docs/code_overview/other.rst
- docs/code_overview/other/config.rst
- praw/reddit.py
This fix removes three incorrect class references. The `Session` class from Requests is mentioned, so I linked to their documentation. The `Config` class from PRAW didn't have a documentation page, so I added that at @bboe's request. The last reference is formatted incorrectly, so I fixed that.
* https://praw.readthedocs.io/en/v6.3.1/code_overview/reddit_instance.html#praw.Reddit.__init__
> Fix class references in Reddit class documentation

- .travis.yml
As of `pydocstyle` version 4.0.0, running `pydocstyle praw` results in many `D412` errors such as 
```
praw/models/inbox.py:154 in public method `message`:
D412: No blank lines allowed between a section header and its content ('Example')
```
I think we should fix or maybe ignore these, but for now we can avoid them by limiting the version of `pydocstyle`.
> Temp-fix travis config by limiting pydocstyle version.

- praw/models/reddit/comment.py
- praw/models/reddit/live.py
- praw/models/reddit/modmail.py
- praw/models/reddit/submission.py
- tests/integration/models/reddit/test_comment.py
The `Comment.replies` attribute begins as `None` and transitions to an empty list after a fetch. The fetch doesn’t retrieve the comment’s replies, retrieving replies is what `.refresh()` is for hence the transition to a list can be confusing.
This PR makes it so that `.replies` is initialised as an empty list so that its value doesn’t change after a fetch. I’ve chosen an empty list instead of `None` so that its type is consistent.
> Initialise `.replies` to an empty list

- praw/models/reddit/comment.py
Relevant: issues  #1109, #1037
> Document `context` attribute next to `permalink`

- CHANGES.rst
- praw/models/reddit/subreddit.py
- praw/models/reddit/widgets.py
- tests/unit/models/reddit/test_widgets.py
This fix allows the `WidgetEncoder` class to properly JSON-encode `Subreddit` objects, which previously were special-cased in `add_community_list` but not in `update`, which meant that one could create a community list with data that contained `Subreddit` objects, but not update community lists containing the same.
* https://www.reddit.com/r/redditdev/comments/cldr9x/widgets_updating_communitylist_errors_out/
>  Properly JSONize Subreddit objects for widget updates. 

- praw/models/reddit/mixins/__init__.py
The code block for locking a comment/submission is incorrectly
formatted and appears as plain text. This fixes that.
[Here is the current documentation showing the error](https://praw.readthedocs.io/en/latest/code_overview/other/commentmoderation.html#praw.models.reddit.comment.CommentModeration.lock).
Since this is such a small change, I didn't think it was necessary to create an issue or add myself to the `AUTHORS.rst`.
This is my first contribution to someone else's project, so I hope I did it right.
> Fix a small formatting error in documentation

- README.rst
- docs/package_info/references.rst
Regularize the capitalization of:
* Python (should be capitalized)
* Gitter (should be capitalized)
And standardizes the prefix of Reddit subreddits to `r/` from `/r/` and adds it to the codeblock reference for `r/redditdev`. Reddit no longer uses the initial slash in the vast majority of their apps and website, starting from first enabling [the omission several years ago](https://www.reddit.com/r/changelog/comments/38ao4t/reddit_change_automatic_linking_of_rsubreddit_and/). `r/` is the only standard used on both New Reddit and the [mobile apps](https://lh3.googleusercontent.com/VxmUPNZF7ZqwSatquI3QL6PW4DNUBa9tM1gsKUHiNYFn5ZRvdxm6uQPjHUP8_q1_mw=w1440-h740-rw) and sites. `/r/` persists mainly as a legacy styling in areas which have not been updated in a while (for example. moderator …
> Standardizing capitalization and subreddit prefixes in the README

- .github/CONTRIBUTING.md
- praw/models/user.py
Fixes #1142
`reddit.user.moderator_subreddits()` is a method for `reddit.user` that [returns a ListingGenerator of the subreddits that the currently authenticated user is a moderator of](https://praw.readthedocs.io/en/latest/code_overview/reddit/user.html). It works fine, but there is actually a **hard limit of 100 subreddits returned** through this method, and that limit is currently not documented for the method. I tested this with my bot u/AssistantBOT, which is currently moderating 600+ public and private subreddits, and the method only returns the top 100 subreddits it's a mod of, sorted by most subscribers to least subscribers. 
(Copied over from #1142)
This PR documents this limit and also notes the `moderated()` method as an alternative for users who need to grab more than a …
> Added limit documentation for reddit.user.moderator_subreddits()

- AUTHORS.rst
- praw/models/reddit/live.py
- praw/models/reddit/modmail.py
- praw/models/reddit/multi.py
- praw/models/reddit/redditor.py
- praw/models/reddit/subreddit.py
- praw/models/reddit/wikipage.py
- setup.py
Fixes #1145 and others within `models/reddit`.
Added a notice per #1145 of the behavior of `.moderated()` not returning the user's own profile subreddit (`u_USERNAME`). Style fixes for remaining references to Reddit Gold, which is now called Reddit Premium (note that the attribute for a Redditor is still called `is_gold`). Also standardizing subreddit prefixes from the legacy `/r/` to the official `r/`. 
Standardized the capitalization of Markdown as per [the site](https://www.reddit.com/wiki/markdown). 
Also updated an oversight in `setup.py` that says that the minimum is Python 3.4 when it is actually 3.5 per the README. Let me know if I did that wrong.
Also, r/wallpapers still doesn't support the `.random()` feature. Verified that.
> Note for #1145 and style fixes

- .travis.yml
- setup.py
Python 3.8 should be back-compatible with everything on the previous versions, furthermore, I have run the pre_push checks and the unit tests on 3.8 without any new syntax errors or DeprecationWarnings.
> Add support for building on python3.8

- pre_push.py
I feel that there is no reason for pre_push.py to not run the unit tests, so I added in a command to run the unit tests. 
I also moved around imports and changed the return of the main function to be the int of the opposite of the value of success (True=0 and False=1).
> Expand on and restructure pre_push.py

- .gitignore
Such patterns should be placed in a global gitignore:
https://help.github.com/en/github/using-git/ignoring-files#create-a-global-gitignore
* 
*
> Remove non-project gitignore patterns

- praw/objector.py
Parent: #1164 
Type hints: 
- praw/objector.py
> Add py3.5 compatible stubs to objector.py

- praw/config.py
- praw/const.py
- praw/endpoints.py
- praw/exceptions.py
Parent PR: #1164 
Combines:
- #1169 
- #1170 
- #1171 
This PR adds type hints and makes them compatible for Python 3.5, which supports type hinting in functions only.
Py 3.5 compatible:
```python
def test_function(arg1: str, arg2: str) -> Dict[str, str]:
return {arg1: arg2}
```
Py 3.6+ compatible:
```python
class Test:
classDict: Dict[str, str]
def test_function(self, arg1: str, arg2: str) -> None:
self.classDict = {**self.classDict, **{arg1: arg2}}
```
> Add Py35 compatible type hints

- praw/util/__init__.py
- praw/util/snake.py
The util package has a bunch of functions in the __init__.py file, and I thought that this was weird, since it breaks the existing norms for seperating. In this PR, I propose putting them into their own file and then importing the functions, so everything is compatible with previous versions.
> Move the snake case functions into their own module

- docs/package_info/references.rst
Just general clean-up for the references file. 
- Noting that the Reddit source code on GitHub [has been archived and is no longer reflective of the current state](https://www.reddit.com/r/changelog/comments/6xfyfg/an_update_on_the_state_of_the_redditreddit_and/).
- Updating from the old FAQ link to the current knowledge base.
- Updating the Reddit Status Twitter link directly to the Reddit Status site.
> Updating References

- praw/reddit.py
> (#1164) Type annotate reddit.py

- praw/util/cache.py
#1164 
-> ./praw/utils/cache.py
> (#1164) Add types to cache.py

- praw/models/auth.py
#1164 
-> ./praw/models/auth.py
> (#1164) Type annotate auth.py

- praw/models/inbox.py
#1164 
-> ./praw/models/inbox.py
> (#1164) Add types to inbox.py

- praw/models/reddit/redditor.py
#1164 
-> ./praw/models/reddit/redditor.py
> (#1164) Add types to reddit/redditor.py

- praw/models/listing/mixins/redditor.py
#1164 
-> ./praw/models/listing/mixins/redditor.py
> (#1164) Add types to listing/mixins/redditor.py

- .github/workflows/pythonpackage.yml
- pre_push.py
Addressing #1175 , I came up with a way to make pre_push work for Windows, and to avoid future errors, suggest using Github's Actions (supporting multiple OS architectures) on top of existing CI to make sure that code works perfectly on all OS. Coverage is also tested, although not put into a easy-to-use website like coveralls, so I suggest this supplement our CI, not be a full replacement, although it easily can replace travis.
> Add Github Actions CI Testing

- praw/models/reddit/removal_reasons.py
#1164 
-> ./praw/models/reddit/removal_reasons.py
> (#1164) Add types to models/reddit/removal_reasons.py

- tests/unit/util/test_snake.py
Both snake functions are not tested, so I added in a test for it.
> Rename snake tests

- praw/models/listing/mixins/subreddit.py
#1164 
-> ./praw/models/listing/mixins/subreddit.py
> (#1164) Add types to listing/mixins/subreddit.py

- praw/exceptions.py
An instance of APIException can have the third parameter be None, but that was not indicated, so I indicated it with an `Optional[str]` argument.
> Fix for exceptions

- docs/package_info/contributing.rst
- tests/conftest.py
- tests/integration/__init__.py
This feature provides the ability to use a refresh token instead of username/password auth for tests.
> Allow use of refresh token instead of username/password in tests

- README.rst
According to https://www.contributor-covenant.org/:
> If you are using a markdown README file in your source code repository, you may want to add a badge like this one Contributor Covenant Badge using the code below.
> 
> `[![Contributor Covenant](https://img.shields.io/badge/Contributor%20Covenant-v2.0%20adopted-ff69b4.svg)](code-of-conduct.md)`
> 
> The Contributor Covenant is released under the Creative Commons Attribution 4.0 International Public License, which requires that attribution be included.
> Add contributer covenant badge

- praw/models/comment_forest.py
- praw/models/helpers.py
- praw/models/inbox.py
- praw/models/listing/mixins/base.py
- praw/models/listing/mixins/redditor.py
- praw/models/listing/mixins/submission.py
- praw/models/listing/mixins/subreddit.py
- praw/models/reddit/comment.py
- praw/models/reddit/emoji.py
- praw/models/reddit/live.py
- praw/models/reddit/mixins/__init__.py
- praw/models/reddit/mixins/editable.py
- praw/models/reddit/mixins/gildable.py
- praw/models/reddit/mixins/inboxable.py
- praw/models/reddit/mixins/inboxtoggleable.py
- praw/models/reddit/mixins/messageable.py
- praw/models/reddit/mixins/replyable.py
- praw/models/reddit/mixins/reportable.py
- praw/models/reddit/mixins/savable.py
- praw/models/reddit/mixins/votable.py
- praw/models/reddit/modmail.py
- praw/models/reddit/multi.py
- praw/models/reddit/redditor.py
- praw/models/reddit/removal_reasons.py
- praw/models/reddit/submission.py
- praw/models/reddit/subreddit.py
- praw/models/reddit/wikipage.py
- praw/models/util.py
According to [this stackoverflow answer](https://stackoverflow.com/a/35174436/) the `code::` and `code-block::` directives function similarly when using Sphinx, but `code-block::` should be used over `code::` if using Sphinx. The advantage of `code::` is that it works in a standalone reStructuredText file (not parsed by Sphinx) but since it's being used in doc strings which are only obtained through Sphinx, it would make sense to replace all of the `code::` directives with `code-block::` directives.
> Standardize usage of code-block

- tox.ini
Python 3.8 is supported and officially tested in,so it should be included.
Refresh tokens can be used, so it should be included.
> Add missing py3.8 and missing refresh_token attr to tox.ini

- CHANGES.rst
- praw/exceptions.py
- tests/integration/models/reddit/test_widgets.py
- tests/unit/test_exceptions.py
While writing stubs, I was looking through the code and realized there is still a lot of Python2 compliant code. This was a simple fix to remove unicode prefixes on a bunch of items. However, several things still do a whole bunch of weird things to deal with unicode. An example is the Praw API Exception, which escapes unicode characters. In Python3, this should not be done, and I will implement a fix for that later.
> Remove unicode string indicatiors

- tests/unit/test_exceptions.py
This does nothing and is not needed in Python3.
> Remove useless coding tag

- .github/CONTRIBUTING.md
- README.rst
- docs/package_info/contributing.rst
Travis is being phased out for Github Actions, but Travis is still referenced in documentation.
Coveralls is also being phased out, but as coverage data is still submitted there, I left the coveralls information.
> Remove references to Travis in documentation

- praw/models/reddit/comment.py
- praw/models/reddit/submission.py
Fix #1291 
This feature provides a note stating the values that can be used with comment_sort.
* Comment sort options on a reddit post
> Add note with appropriate values for comment/reply sort

- praw/models/reddit/comment.py
- praw/models/reddit/redditor.py
- praw/models/reddit/submission.py
- praw/reddit.py
This saves 34% of time when running a calculation.
Test:
```python
In [2]: from timeit import timeit   
In [4]: timeit("(1, 2, 3).count(1)")                                                                                                                                               
Out[4]: 0.08089671100000118
In [5]: timeit("[1, 2, 3].count(1)")                                                                                                                                               
Out[5]: 0.12496681500000051
In [8]: ((timeit("(1, 2, 3).count(1)") - timeit("[1, 2, 3].count(1)")) / timeit("[1, 2, 3].count(1)")) * 100                                                                       
Out[8]: -34.34746208108047
```
> Change [...].count() to (...).count() to decrease run time by 1/3

- AUTHORS.rst
- CHANGES.rst
- praw/models/redditors.py
- praw/reddit.py
- tests/integration/cassettes/TestRedditors.test_partial_redditors.json
- tests/integration/cassettes/TestRedditors.test_partial_redditors__not_found.json
- tests/integration/models/test_redditors.py
- tests/unit/models/test_redditors.py
Relevant: issue #1108.
The new `Redditors.user_data_by_account_ids()` method hits up the `/api/user_data_by_account_ids` endpoint.
I anticipate the only use case of this method would be to bulk convert Redditor ids to usernames, so I’ve decided to have it just return raw dictionaries rather than redditor instances.
> Add `Redditors.user_data_by_account_ids()`

- CHANGES.rst
- praw/models/user.py
- tests/integration/cassettes/TestUser.test_friend_exist.json
- tests/integration/cassettes/TestUser.test_friend_not_exist.json
- tests/integration/models/test_user.py
I am aware that you can get friend data from `Redditor.friend_info`, but it requires creation of a Redditor object and this PR makes it clear that the function is to check if you are friends with i.e., a suspended or shadowbanned user. 
Fix 1 for #1241
> Add method to retrieve friend data from users.friends

- praw/models/listing/mixins/redditor.py
- praw/models/reddit/message.py
- praw/models/reddit/redditor.py
- praw/models/reddit/subreddit.py
Adds notes for #1241 and #1043
> Add documentation notes for outstanding issues

- docs/getting_started/authentication.rst
This fixes the bullet points on the authentication documentation page. The highlighted text (below) should be sub-bullet points, not appearing in-line.
> Fix indentation on documentation

- .github/workflows/ci.yml
Proposing using the latest version of `actions/checkout` in the GitHub Actions workflow here - `v2`.
* https://github.com/actions/checkout#checkout-v2
> Update actions/checkout version

- README.rst
`subreddit.moderator` results in an instance of `ModeratorRelationship`, which is not iterable. Instead, it is callable, so it needs to be called. 
```
>>> for moderator in reddit.subreddit('redditdev').moderator:
...     print(moderator)
... 
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
TypeError: 'ModeratorRelationship' object is not iterable
```
> Fix documentation that contained invalid code

- praw/models/reddit/comment.py
t1_ are comments, t3_ are links (submissions)
Fixes a mistake that snuck in with #1392
> Documentation: wrong prefix

- .github/workflows/ci.yml
The coverallsapp/github-action runner made changes to how parallel jobs are run. We should update our `ci.yml` to support these changes, but for now this PR pins an old version of the CI runner.
* https://github.com/coverallsapp/github-action/commit/198c7931d32bc4bfa3768f698af3332214dae75f
* #1400
> Limit coverallsapp/github-action version

- setup.py
- tests/integration/models/reddit/test_collections.py
- tests/integration/models/reddit/test_comment.py
- tests/integration/models/reddit/test_emoji.py
- tests/integration/models/reddit/test_live.py
- tests/integration/models/reddit/test_message.py
- tests/integration/models/reddit/test_modmail.py
- tests/integration/models/reddit/test_multi.py
- tests/integration/models/reddit/test_redditor.py
- tests/integration/models/reddit/test_removal_reasons.py
- tests/integration/models/reddit/test_submission.py
- tests/integration/models/reddit/test_subreddit.py
- tests/integration/models/reddit/test_widgets.py
- tests/integration/models/reddit/test_wikipage.py
- tests/integration/models/test_comment_forest.py
- tests/integration/models/test_inbox.py
- tests/integration/models/test_preferences.py
- tests/integration/models/test_redditors.py
- tests/integration/models/test_subreddits.py
- tests/integration/models/test_trophy.py
- tests/integration/models/test_user.py
- tests/integration/test_reddit.py
- tests/unit/models/test_redditors.py
- tests/unit/test_config.py
- tests/unit/test_reddit.py
The mock module is just a backport of the mock module, and as the
minimum version comes with the unittest.mock module, there is no need to
keep on installing another dependency.
> Use unittest.mock over mock package

- docs/getting_started/configuration/prawini.rst
This should be ideally been catched during code review.
> Forgot to close parenthesis

- AUTHORS.rst
- CHANGES.rst
- praw/models/reddit/subreddit.py
- tests/integration/cassettes/TestSubredditFlair.test_update_quotes.json
- tests/integration/models/reddit/test_subreddit.py
This  fixes a bug in `SubredditFlair.update`. The Reddit API uses Python's CSV reader, which expects embedded double-quotes to be escaped, and PRAW's current method does not do this. Double-quotes can appear in flair_text values, which means that `SubredditFlair.update` sets flair_texts with double-quotes to incorrect values. For example,  
reddit.subreddit('TEST_SUBREDDIT').flair.update(['MaybeNetwork'],text='"Quotes"')
will set the flair_text to `Quotes""` instead of `"Quotes"`, and 
reddit.subreddit('TEST_SUBREDDIT').flair.update(['MaybeNetwork'],text='"quote", unquote, "quote"')
will fail entirely instead of setting the flair_text to `"quote", unquote, "quote"`.
This proposed fix uses `writer` from Python's CSV module to ensure that inputs have the expected escaping.
---
There are a …
> Fix bug in SubredditFlair update method

- praw/models/helpers.py
- praw/models/preferences.py
- praw/models/reddit/emoji.py
- praw/models/reddit/live.py
- praw/models/reddit/multi.py
- praw/models/reddit/removal_reasons.py
- praw/models/reddit/subreddit.py
- praw/models/reddit/widgets.py
- praw/models/reddit/wikipage.py
- praw/models/trophy.py
This reverts commit 698b103514932424a222edfadd6ea735db76e954.
Fix #1447
> Revert "Get rid of redundant ``'<content>'``"

- praw/models/reddit/comment.py
- praw/models/reddit/live.py
- praw/models/reddit/message.py
- praw/models/reddit/modmail.py
- praw/models/reddit/multi.py
- praw/models/reddit/redditor.py
- praw/models/reddit/removal_reasons.py
- praw/models/reddit/submission.py
- praw/models/reddit/subreddit.py
- praw/models/reddit/widgets.py
- praw/models/reddit/wikipage.py
- praw/models/stylesheet.py
- praw/models/trophy.py
I believe I was the one who originally came up with the stilted phrasing that the list was "not comprehensive in any way." The revised phrasing of "not necessarily comprehensive" is more accurate and less awkward.
I went through and changed the old phrasing everywhere I found it to use the new one.
Also, `black` insisted on making some formatting changes, for some reason.
> Update phrasing about comprehensiveness of documented attributes

- .github/workflows/ci.yml
> Remove build directory

- praw/reddit.py
- tests/unit/test_reddit.py
This parameter gets passed through to `requests`, which automatically JSON-encodes the value and sets an appropriate Content-Type header.
Support for sending bodies that are actually JSON-encoded is needed for upcoming PRAW features such as polls.
This will help for a fix for #1452 by allowing us to use new endpoints.
> Add json parameter for POST, PATCH, and PUT

- .github/workflows/ci.yml
- tests/integration/test_github_actions.py
This will make sure that basic functionality is not broken by any
commits.
TODO: Add environment variables so that this test works
> Add actual network-requesting test

- tests/integration/test_github_actions.py
Secrets are not copied to forks, so the program won't run anywhere else.
> Skip if not in praw-dev/praw repo

- .github/workflows/ci.yml
The purpose of this environment variable was to let the action know it's running from Github Actions, but since we directly test the presence of the client-id, it is no longer needed.
> NETWORK_TEST env variable no longer needed

- docs/getting_started/configuration/options.rst
These parameters do not have any documentation, so they should be documented along with all of the other options.
> Add entries about ratelimit_seconds and timeout

- CHANGES.rst
- praw/models/reddit/emoji.py
- praw/models/reddit/modmail.py
- praw/models/reddit/multi.py
- praw/models/reddit/removal_reasons.py
- praw/models/reddit/subreddit.py
- praw/models/reddit/widgets.py
- praw/reddit.py
This feature provides a `.delete()` method on the `Reddit` class. We already have similar methods `get`, `post`, `patch`, and `put`. It's nice to filter all the HTTP DELETE requests through this method to ensure consistency and reduce duplication.
> Create Reddit.delete() method

- praw/models/front.py
- praw/models/inbox.py
- praw/models/listing/generator.py
- praw/models/listing/mixins/base.py
- praw/models/listing/mixins/gilded.py
- praw/models/listing/mixins/redditor.py
- praw/models/listing/mixins/rising.py
- praw/models/listing/mixins/submission.py
- praw/models/listing/mixins/subreddit.py
- praw/models/reddit/base.py
- praw/models/reddit/live.py
- praw/models/reddit/multi.py
- praw/models/redditors.py
- praw/models/subreddits.py
- praw/models/user.py
- praw/reddit.py
This is two different type-related fixes:
First, a bunch of functions claim to return a `Generator` while returning a `ListingGenerator` which technically does not satisfy the contract to be a `Generator`, though it does satisfy the `Iterator` contract. I've updated the `ListingGenerator` class to inherit from `Iterator` and updated the type signatures referencing `Generator`.
Second, I updated miscellaneous type signatures in places where PyCharm indicated they were incorrect.
https://docs.python.org/3/library/typing.html#typing.Generator
> Generator -> Iterator, and other type fixes

- praw/models/reddit/redditor.py
A minor correction in the `Redditor.trophies` method.
> Minor correction

- praw/models/reddit/comment.py
This mistake was caught by flake8: the `.format()` call wasn't using one of its arguments because it was mistakenly using the name of the class in place of the fullname of the relevant comment. Presumably this happened because the code was modified from previous code that changed the error message depending on the class.
> Bugfix: Correct error message when we fail to fetch a comment

- .github/workflows/ci.yml
Reverts praw-dev/praw#1457
Pip has pushed version 20.1.1, which reverts the old behavior. Now, this code leads to all builds failing.
> Revert "Remove build directory"

- CHANGES.rst
- docs/code_overview/other.rst
- docs/code_overview/other/calendarconfiguration.rst
- docs/code_overview/other/hover.rst
- docs/code_overview/other/styles.rst
- praw/models/__init__.py
- praw/models/reddit/widgets.py
Linked to #1435 
This feature provides objects for any dictionaries that are provided as parameters.
Each commit contains a link to where the common attributes for that class were found.
* Updates to Button class: https://github.com/praw-dev/praw/pull/1506/commits/fbde0e4342f9adb4d391e6654049f775db0e7afa
* CalendarConfiguration: https://github.com/praw-dev/praw/pull/1506/commits/68742ef3f70483447a15536afd88c61c5c4a0dcc
* Hover: https://github.com/praw-dev/praw/pull/1506/commits/60d77286806b0b3f1e1288d794e922951c5b190c
* Styles: https://github.com/praw-dev/praw/pull/1506/commits/2e39d72213192ce85d3f8562fa043fb3bc70c081
> Generate objects for dictionary parameters

- praw/models/reddit/subreddit.py
For some reason `SubredditModeration.stream` was manually acting as a cached property instead of using the `@cachedproperty` decorator.
> Make SubredditModeration.stream a cached property.

- praw/models/reddit/comment.py
Both properties are the same, but fullname does not require a network request to be made.
> Use fullname instead of name

- praw/models/reddit/subreddit.py
The documentation for the `submit_poll` function mistakenly used `submit` rather than `submit_poll` in its example.
Also, `black` decided that some other parts of the file needed changing.
> Fix submit_poll documentation

- AUTHORS.rst
- praw/models/reddit/comment.py
- praw/models/reddit/message.py
Fixes #1495
This just adds `body_html` to the doc strings of `Comment`, `Message`, and `SubredditMessage`. The latest version of `praw` seems to have this attr available for `Comment`
> docs: add body_html to doc strings..update AUTHORS.rst [#1495]

- pre_push.py
Since Windows and all Unix-based OSes have different conventions on process initialization, check_call needs to always be a list, so that Python can accomondate each operating system. The changed line translates as "execute a file named `black ..exe`", not "execute a file named `black.exe` with a parameter of `.`", as it does on Unix. The fix just converts the list of arguments to an actual list of arguments.
> Fix pre-push script to work on Windows

- CHANGES.rst
- praw/models/reddit/subreddit.py
This fixes a bug when the user is using token auth and then tries to leave as a moderator from a subreddit.
> Fix bug with leaving as a moderator when using token auth

- AUTHORS.rst
- praw/models/reddit/subreddit.py
This feature provides updated documentation that adds the newly added appeals state to modmail conversations. 
* https://www.reddit.com/dev/api/#GET_api_mod_conversations
> Docs updated: appeals state modmail conversations.

- CHANGES.rst
- praw/models/reddit/submission.py
- tests/unit/models/reddit/test_submission.py
This feature provides the ability to pass gallery urls (https://www.reddit.com/gallery/abc123) to `reddit.submission`.
*  https://github.com/praw-dev/praw/issues/1549#issuecomment-678371873
> Add support for gallery urls

- praw/models/reddit/subreddit.py
This fixes just the documentation issue mentioned in #1565.
> Fix modmail stream doc reference to "messages"

- README.rst
- docs/getting_started/multiple_instances.rst
This adds a mention for Async PRAW as I am seeing more people using PRAW with discord bots which can cause unexpected bot crashes if PRAW blocks too long.
> Add mention for Async PRAW

- praw/models/reddit/comment.py
Just a small thing I noticed while reading the docs. The newline got deleted with 24bc2602d4034b3fb9302456261b7b2025cb426d and currently leads to badly rendered docs at https://praw.readthedocs.io/en/latest/code_overview/models/comment.html#praw.models.Comment.replies
> Add newline to fix reST syntax

- praw/models/reddit/subreddit.py
Updated the `modmail_conversations()` doc string to reflect the full list of states that you can use per the official API. Also clarified what `all` and `inbox` actually include
Just documentation fixes
* [Reddit API](https://www.reddit.com/dev/api/oauth#GET_api_mod_conversations)
> Updated documentation for modmail conversation

- praw/models/util.py
- tests/unit/models/test_util.py
This PR changes the `BoundedSet` class used for streams to evict its least-recently-used element, rather than its oldest element.
The change includes a unit test where elements are duplicated in the stream. In this test, new items are added and removed from the head of the listing one one at a time. Even though the original items are seen at least every other fetch, the new items end up filling the cache and causing us to forget the old items.
I think I've seen behavior like this in production, though I don't have proof. In a slow-moving subreddit where a lot of submissions get removed, we've seen duplicates in the `submissions` stream. I think this scenario is basically similar to the test case, in that a high proportion of newly-seen items don't remain present in the listing.
It's …
> Use least-recently-used eviction policy for stream BoundedSet

- CHANGES.rst
This adds a changelog entry for the new storage mechanism because it may behave differently than it has been before the changes.
> Add changelog entry for #1547

- CHANGES.rst
The new entry, under "Fixes," describes the change to stream behavior.
There is already an entry under "Changes" describing the addition to `BoundedSet`, but users are more likely to care about the change to streams.
> Add another changelog entry for #1547

- docs/package_info/praw7_migration.rst
There is a small typo in docs/package_info/praw7_migration.rst.
Should read `received` rather than `recieved`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md
> docs: fix simple typo, recieved -> received

- .github/workflows/ci.yml
- docs/conf.py
- praw/models/auth.py
- praw/models/reddit/comment.py
- praw/models/subreddits.py
- pre_push.py
- pyproject.toml
- setup.py
- tests/integration/__init__.py
- tests/integration/models/reddit/test_live.py
- tests/integration/models/reddit/test_subreddit.py
- tests/unit/models/reddit/test_collections.py
- tests/unit/models/reddit/test_inline_media.py
- tests/unit/models/reddit/test_rules.py
- tests/unit/models/reddit/test_subreddit.py
- tests/unit/models/test_util.py
- tools/check_docstring.py
This sorts all imports as recommended in the [contributing](https://github.com/praw-dev/praw/blob/c74a5e81a93fe49f5957adc82bc7db9a649196d8/.github/CONTRIBUTING.md#import-statement-order) guidelines. It also adds a step to `pre_push.py` and GitHub Actions for enforcement.
- #1599
> Sort all imports with isort

- docs/getting_started/multiple_instances.rst
- praw/config.py
- praw/reddit.py
- tests/unit/test_reddit.py
This adds a check to see if PRAW is being ran in an asynchronous environment (more specifically, if there is a running asyncio event loop) and advise users to use Async PRAW if there is one running.
This adds a check that is ran on the initialization of `praw.Reddit` and every time `Reddit.request()` is called. It can be suppressed by passing `check_for_async=False` anywhere config options are accepted.
> Add check to see if PRAW is being ran in an asynchronous environment

- CHANGES.rst
- praw/reddit.py
- tests/integration/models/reddit/test_modmail.py
Fixes #1636
This fixes a bug introduced with https://github.com/praw-dev/praw/commit/cd8ab625c88d14efb18f961d1365a8dce1a121e9 and switches to an alternative way for PRAW to check if it is being ran in an asynchronous environment.
This also fixes a test with an unsupported method, `datetime.fromisoformat`.
> Fixes for 3.6

- .github/workflows/prepare_release.yml
- .github/workflows/pypi.yml
- .github/workflows/tag_release.yml
- tools/bump_version.py
Only pull requests created through the prepare_release action will be tagged on merge.
> Tag release on merge and then publish to pypi

- CHANGES.rst
- praw/reddit.py
> Broaden exception catch for async check

- .github/workflows/pypi.yml
- .github/workflows/tag_release.yml
Using a draft is necessary because one github action will not result in
automatically triggering a separate action. Thus we create a draft, because the
manual publishing of the draft will cause the publish to pypi action to
trigger.
> Tag release only makes a draft release

- praw/reddit.py
This makes the generator in `Reddit.info` actually use the parameter being passed in instead of use a variable defined in the outer scope.
> Rename parameter in Reddit.info.generator and actually use parameter instead of one from outer scope

- docs/conf.py
This changes the following:
- Make copyright year dynamic to always return the current year
- Make intersphinx link to the latest Python docs
> Update Sphinx config

- praw/models/reddit/subreddit.py
- praw/models/reddit/wikipage.py
This is the typed version of subreddit.py
> Type subreddit

- praw/util/token_manager.py
- tests/unit/test_reddit.py
- tests/unit/util/test_token_manager.py
This allows IDEs and other tools to recognize that the class is abstract and throws the appropriate warnings.
> Use the ABC class to declare an abstract class

- AUTHORS.rst
- praw/models/reddit/submission.py
Closes #1700 
Docs reflect that link_flair_template_id attribute does not return None when a link flair isn't present
> update docs for Submission.link_flair_template_id

- CHANGES.rst
- docs/code_overview/other.rst
- docs/code_overview/other/moderatedlist.rst
- praw/models/__init__.py
- praw/models/list/moderated.py
- praw/models/reddit/redditor.py
- praw/objector.py
- praw/reddit.py
This makes the `Redditor.moderated()` method actually utilize all the data that is returned from the API.
Currently, this method just uses the `sr` key to initialize a lazy subreddit instance from what is returned:
```json
{
"banner_img": "",
"community_icon": "",
"display_name": "pics",
"title": "Reddit Pics",
"over_18": false,
"icon_size": [
256,
256
],
"primary_color": "#ffffff",
"icon_img": "https://b.thumbs.redditmedia.com/VZX_KQLnI1DPhlEZ07bIcLzwR1Win808RIt7zm49VIQ.png",
"display_name_prefixed": "r/pics",
"sr_display_name_prefixed": "r/pics",
"subscribers": 26892797,
"whitelist_status": "all_ads",
"subreddit_type": "public",
"key_color": "#222222",
"name": "t5_2qh0u",
"created": 1201249869.0,
"url": "/r/pics/",
"sr": "pics",
"created_utc": 1201221069.0,
"banner_size": null, …
```
> Make Redditor.moderated utilized all data returned from the API

- AUTHORS.rst
Doesn't change any functionality.
RST doesn't use HTML style (``) comments, but instead every block which isn't a valid markup construct is treated like a comment.
Surprised this wasn't fixed for 14 months. 👍
> Convert HTML comments to RST in AUTHORS.rst

- CHANGES.rst
- praw/exceptions.py
- praw/reddit.py
- tests/integration/cassettes/TestWikiPage.test_content_md__invalid_name.json
- tests/integration/models/reddit/test_wikipage.py
Reddit.request currently cannot handle Bad Requests when the JSON data only contained the keys "reason" and "message". The wiki endpoints are FULL of 400s, 403s, and 404s that return responses with only those fields—more details to follow in coming PR that adds endpoints `api/wiki/hide` and `api/wiki/revert`. Reddit.request currently assumes that bad requests either [have the keys "error" and "message"](https://github.com/praw-dev/praw/blob/master/praw/reddit.py#L868), or [contain the key "explanation"](https://github.com/praw-dev/praw/blob/master/praw/reddit.py#L876).
This PR includes a test and a cassette that shows this kind of response. You could also execute `reddit.subreddit('reddit.com').wiki['\\A'].content_md` in the current build to see this.
> Fix bug where Reddit.request could not handle certain Bad Requests

- pre_push.py
- pyproject.toml
This just adds `.venv*` to the excluded files/folders for pre_push.py checks.
> Exclude paths that start with .venv from pre_push checks

- CHANGES.rst
- docs/code_overview/other.rst
- docs/code_overview/other/fullnamemixin.rst
- praw/models/reddit/mixins/fullname.py
- tests/integration/cassettes/TestUser.test_blocked_fullname.json
- tests/integration/models/test_user.py
Unfortunately, Reddit is inconsistent about the difference between an id and a fullname. The API sometimes returns fields marked "id" that are actually fullnames. For example, if you have no blocked users, executing 
reddit=praw.Reddit()
reddit.redditor("PyAPITestUser3").block()
blocked = next(iter(reddit.user.blocked()))
blocked.fullname
produces ``t2_t2_6c1xj``, because Reddit's response to reddit.user.blocked() is 
{'kind': 'UserList', 'data': {'children': [{'date': 1622757760.0, 'rel_id': 'r9_2mb7wa', 'name': 'PyAPITestUser3', 'id': 't2_6c1xj'}]}}
This PR changes FullnameMixin.fullname so that it checks for underscores in ids. 
Docs were modified so that the method could be referenced in CHANGES.rst.
Possibly related to [this.](https://github.com/praw-dev/praw/issues/1437#issuecomment- …
> Fix bug in FullnameMixin.fullname

- CHANGES.rst
- praw/endpoints.py
- praw/objector.py
- praw/reddit.py
- tests/integration/cassettes/TestReddit.test_username_available__available.json
- tests/integration/cassettes/TestReddit.test_username_available__unavailable.json
- tests/integration/cassettes/TestReddit.test_username_available_exception.json
- tests/integration/test_reddit.py
Adds the /api/username_available endpoint and method Redditor.available.
The username_available endpoint was removed in commit 7a72c1e because [at the time](https://web.archive.org/web/20161108093457/https://www.reddit.com/dev/api#GET_api_username_available) it was a non-oauth endpoint. It is [now](https://www.reddit.com/dev/api#GET_api_username_available) an oauth endpoint, so it can be re-added. This endpoint can return bools, so objector.py needed a small tweak.
* https://web.archive.org/web/20161108093457/https://www.reddit.com/dev/api#GET_api_username_available
* https://www.reddit.com/dev/api#GET_api_username_available
> Add oauth endpoint username_available

- praw/models/comment_forest.py
Fixes #1716 
I added a warning about making concurrent requests to the morechildren endpoint. Now that https://github.com/praw-dev/prawcore/pull/112 has been merged, the documentation can mention the new TooManyRequests exception that can be triggered when this happens.
I also updated the documentation about the maximum number of comments returned in each request. The number is now 100, and that number refers to the number of *comments* returned, not comments and morechildren instances (and not the maximum number of comments you can include in a request). In the test I ran, the number of comments returned was indeed capped at 100. but the total of comments + more instances returned in each request reached as high as 140.
* https://github.com/praw-dev/prawcore/pull/112
* …
> Add warning about concurrent use of CommentForest.replace_more

- CHANGES.rst
This combines and moves the deprecated section to the correct spot in the change log.
> Combine deprecated sections

- AUTHORS.rst
- praw/models/reddit/redditor.py
Submissions were previously omitted
Fixes #
This merely fixes a minor error in the docs.
> Added submissions to attribute list in docs

- praw/reddit.py
This fixes the example and a spelling mistake in the `username_available` docs.
> Fix example in username_available docs

- CHANGES.rst
- praw/endpoints.py
- praw/models/reddit/submission.py
- tests/integration/cassettes/TestSubmissionModeration.test_update_crowd_control_level.json
- tests/integration/models/reddit/test_submission.py
Adds :meth:`.SumissionModeration.update_crowd_control_level`, which allows moderators to toggle the crowd control level of a single post. The table of level descriptions was taken from [here](https://mods.reddithelp.com/hc/en-us/articles/360038129231-Crowd-Control-).
This method raises a generic 403 when it is used on posts you don't have permissions for, or on posts that doesn't exist.
If you set `level` to some integers below 0, it sets the level to 0, and similarly, using some integers above 4 will set the level to 3. 
* https://www.reddit.com/dev/api#POST_api_update_crowd_control_level
* https://mods.reddithelp.com/hc/en-us/articles/360038129231-Crowd-Control-
> Add SubmissionModeration.update_crowd_control_level

- CHANGES.rst
- praw/models/reddit/redditor.py
- praw/models/user.py
- tests/integration/cassettes/TestUser.test_moderator_subreddits.json
- tests/integration/models/test_user.py
Unfixes 1333
Issue 1142 reported that `User.moderator_subreddits` would not return more than 100 subreddits, and this information was added to the documentation in 1145. The method was deprecated in 1148, with a note to use `Redditor.moderated` instead, and was removed in 1333.
I suspect that the report of the alleged limitation of `User.moderator_subreddits` was not correct, and may have just been the result of a misunderstanding of how `ListingGenerator` works. I tested the sister method of `User.moderator_subreddits`, `User.subreddits`, and found that it also returns only 100 subreddits if you call `list(reddit.user.subreddits())`. But that happens because `ListingGenerator`s default value for `limit` is 100. If you call `list(reddit.user.subreddits(limit=None))`, the ListingGenerator …
> Restore User.moderator_subreddits

- CHANGES.rst
- docs/getting_started/configuration/options.rst
- praw/config.py
- praw/models/reddit/submission.py
- tests/unit/models/reddit/test_submission.py
Print a warning if the `comment_sort` field is set on a submission after the fetch has already happened. Hopefully this will reduce issues with users wondering why they are changing the sort without any effect.
https://www.reddit.com/r/redditdev/comments/ovr7na/praw_how_to_sort_comments/
First draft, wanted to get feedback on whether it's worth adding a config field to turn this off. There could be a viable use case for people who want to set the sort, fetch comments, change the sort and fetch again, and it would be annoying to have the log message each time. On the other hand that would be really rare (and avoidable by just recreating the submission instance), so I'm not sure whether it's worth "polluting" the config docs/code with a field almost no one will ever set.
Also not sure if …
> Print warning when comment_sort is set after fetch

- CHANGES.rst
- praw/models/reddit/subreddit.py
- tests/integration/cassettes/TestSubredditLinkFlairTemplates.test_user_selectable.json
- tests/integration/models/reddit/test_subreddit.py
Currently there's no way for a non-moderator to get a list of available flair templates without an existing submission. 
https://praw.readthedocs.io/en/latest/code_overview/models/submission.html#praw.models.Submission.flair
only works if you have a submission to call it on.
https://praw.readthedocs.io/en/latest/code_overview/other/subredditflair.html#praw.models.reddit.subreddit.SubredditFlair.link_templates
only works if you're a moderator.
Sometime reddit added a `is_newlink` parameter to the `flairselector` endpoint so you can call it without a submission.
Starting point for discussion, I'm not quite sure where this function should live or what it should be called. From a users perspective, it functions very similarly to the moderator endpoint, but it returns slightly different …
> Add new function for getting list of flair templates

- .github/workflows/ci.yml
The coverallsapp in GitHub actions was pinned to a particular commit from a year ago. It was done here https://github.com/praw-dev/praw/pull/1402 
This branch pins itself to the master branch of coverallsapp to avoid technical debt.
Also, for the `coveralls` command, it uses the https://coveralls-python.readthedocs.io/en
instead of https://github.com/bboe/coveralls-python/archive/github_actions.zip
But the coveralls-python seems to be maintained and up to date.
I am not too convinced about this. 
FYI: Ideally, we would not be using the coveralls command in section: `Submit to coveralls`. But because of this issue https://github.com/coverallsapp/github-action/issues/30 this seems to be the simpler choice
> Bugfix/coveralls GitHub action updated

- .github/CONTRIBUTING.md
- .github/workflows/ci.yml
- .pre-commit-config.yaml
- docs/package_info/contributing.rst
- pre_push.py
- setup.py
Followup to PR #1774 as requested by @LilSpazJoekp 
Per [my comment](https://github.com/praw-dev/praw/pull/1774#pullrequestreview-734610136) on #1774 :
> Given that all the now-duplicate dep installation and lint runner commands [`lint-multi-os` job](https://github.com/praw-dev/praw/blob/ea14f22c8b5f87516cd1ff7f6b4375d9e11ad1e9/.github/workflows/ci.yml#L11) in your CI workflow (aside from the Sphinx build) is now also covered here, I would suggest replacing all that redundancy with the pre-commit Github action which will install and run them through pre-commit, and tweak your caching as needed. This ensures the same checks are run locally as in the CI (right now some of the invocations are different, because they were changed here but not there, and the versions may drift out of sync), …
> Simplify, unify and document pre_push, CIs and pre-commit hooks to all use consistent tools, versions and config

- CHANGES.rst
- praw/util/token_manager.py
Fixes #1748 
This fixes an import error when using PRAW in environments where `libsqlite3-dev` is needed to utilize the `sqlite3` builtin.
- https://github.com/praw-dev/praw/issues/1748#issuecomment-864178047
> Only import sqlite3 in SQLiteTokenManager class

- praw/models/comment_forest.py
This fixes a typo in the CommentForrest docs.
> Fix typo in CommentForrest docs

- docs/getting_started/configuration/options.rst
- docs/getting_started/ratelimits.rst
- docs/index.rst
Fixes #1777
This adds some clarification in the docs for `ratelimit_seconds`.
> Add clarification for `ratelimit_seconds` in the docs

- setup.py
Fixes #1809
This includes the image that `_upload_media` falls back to when submitting videos.
> Include *.png files

- praw/models/reddit/subreddit.py
- setup.py
Fixes #1813 
Currently, requests is imported at runtime in `praw` but only used for static type annotations, creating an undeclared implicit dependency. In addition, requests is used a number of places in the test suite and development scripts, but not included in the `tests` extra.
While not terribly harmful in practice at the moment (since `prawcore` currently requires requests, albeit indirectly), it results in warnings and confusion in downstream tooling (e.g. conda-forge/praw-feedstock#20 ) and could pose a problem at some point in the future if this is ever dropped or changed.
Thus, on the advice of @LilSpazJoekp , this PR guards the requests import with `if TYPE_CHECKING` and uses a string type annotation, which avoids this problem at runtime; and also adds `requests` to the `test` …
> Guard requests import only needed for mypy & explicitly req for tests

- AUTHORS.rst
- praw/models/reddit/subreddit.py
- tests/unit/models/reddit/test_subreddit.py
This pull request provides a native (prawcore) exception instead of an "requests" exception for one specific function path.
- #1825
> Catch a requests HTTPError and instead raise a prawcore ServerError.

- .github/workflows/ci.yml
Fixes #1843 
Test, confirm and (for now) work around/fix the issue with the pre-commit action on Windows identified in #1843 .
I'll be testing a few things, so I'll leave this as draft for now.
> Fix issue with pre-commit action on Windows

- CHANGES.rst
- praw/objector.py
- tests/unit/models/reddit/test_modmail.py
Fixes #1870 
This changes the objector behavior to not preemptively set ``messages`` or ``mod_actions`` when building `ModmailConversation` objects.
> Don't pre-populate ModmailConversation.messages

- praw/models/reddit/subreddit.py
Fixes #1871
This fixes a typo in the link templates docs.
> Fix typo in docs

- praw/objector.py
Fixes #1870 
This prevents `conversation.obj_ids` from being set when it doesn't have all the object ids. This also sets `conversation.messages` if `num_messages` is 1.
> Don't set conversation.obj_ids since it can be missing data

- AUTHORS.rst
- docs/getting_started/quick_start.rst
Changed subreddit "test" to "learnprogramming" in quick start example
> Update quick_start.rst - fixed typo in docs

- tests/integration/__init__.py
- tests/integration/models/reddit/test_more.py
- tests/integration/models/test_comment_forest.py
- tests/unit/__init__.py
- tests/unit/models/list/test_base.py
- tests/unit/util/test_deprecate_args.py
This fixes a deprecation warning thrown during tests.
- https://docs.pytest.org/en/stable/deprecations.html#support-for-tests-written-for-nose
> Rename `setup` in tests to `setup_method`

- docs/examples/lmgtfy_bot.py
- praw/models/reddit/mixins/editable.py
- praw/models/reddit/mixins/replyable.py
- tests/integration/models/reddit/test_comment.py
- tests/integration/models/reddit/test_submission.py
After getting feedback from various users, positional arguments for `EditableMixin.edit` and `ReplyableMixin.reply` will no longer be deprecated.
> Revert `EditableMixin.edit` and `ReplyableMixin.reply` positional argument deprecation

- praw/models/comment_forest.py
Just a small change in the CommentForest.replace_more method: limit can be `None`, as per documentation.
A small question: Praw has typing annotation but it's not published annotated, is that intended?
> CommentForest: replace_more typing

- praw/models/reddit/removal_reasons.py
- tests/integration/models/reddit/test_removal_reasons.py
Fixes #1924 
A fix for removal reasons being returned in the wrong order.
> Fix removal reason ordering

- MANIFEST.in
- setup.py
Reverts praw-dev/praw#1936
Typing improvement are needed to be made to PRAW before this is fully MyPy compatible. Becoming MyPy compatible may also be problematic as PRAW dynamically defines attributes on deserialized objects from Reddit. 
The reason for the dynamically defining attributes is because Reddit is known for adding and removing attributes without notice and it removes the burden of maintaining accurate attributes on every type that PRAW deserializes from Reddit from PRAW.
> Revert "Add py.typed stub"

- AUTHORS.rst
- praw/models/reddit/mixins/__init__.py
for u/subreddit-ModTeam usage
Adds documentation for the u/subreddit-ModTeam account removal notification
-
> added "public_as_subreddit" type to send_removal_message

- CHANGES.rst
- praw/endpoints.py
- praw/models/reddit/subreddit.py
- praw/reddit.py
- tests/integration/cassettes/TestSubredditFlairTemplates.test_reorder.json
- tests/integration/cassettes/TestSubredditLinkFlairTemplates.test_reorder.json
- tests/integration/models/reddit/test_subreddit.py
I needed the ability to reorder flairs... So I added it.
I added the api path to endpoints.py, and added subreddit.flair.reorder which takes arguments of a list of flair ID's and the flair type as a string.
Hope this is okay
> Added support for reordering flairs through reddit.flair.reorder

- praw/models/reddit/mixins/inboxtoggleable.py
This pull request provides a more explicit description for the `sendreplies` methods, which can only be applied to a thing created by the user.
- https://www.reddit.com/dev/api/#POST_api_sendreplies
> Docs: Add more explicit description about the `sendreplies` methods

- pyproject.toml
This pull request updates pyproject.toml to require a prawcore version 2.4.0 or later. praw 7.8.0 uses the window_core attribute of prawcore.session when initializing an instance of praw.Reddit, which does not exist before version 2.4.0. Although this discrepancy does not cause issues with fresh installs of praw, it may affect users who are upgrading from older version installed before the release of prawcore 2.4.0.
- https://github.com/praw-dev/praw/blob/fdb847e5f0160867b4eb56495fdda0050f13aabd/praw/reddit.py#L553
- https://github.com/praw-dev/prawcore/compare/v2.3.0...v2.4.0#diff-eaadbdb53e986a834aaeaf0846d686305211bcdab6ea8b7a5c99522dd6309190
> Bump prawcore dependency version

- AUTHORS.rst
- praw/config.py
- tests/unit/test_config.py
Hello team,
I've recenlty been trying to learn more about [zipapps](https://docs.python.org/3/library/zipapp.html),
and so I bundled up one of my personal projects to test things out. My project uses
`praw`, and I kept running into configuration errors. I initially thought the problem
was that my `praw.ini` couldn't be found due to file indirection or security limits with
zipapp.
However, after setting some breakpoints and digging through the `praw.config.Config`
source, I realized that `Config` is looking for the default `praw.ini` on the filesystem
relative to the module source file. While this works on standard installs, in a zipapp,
the source files don't actually exist on disk. The default `praw.ini` isn't found, and
`praw.config._config_boolean()` errors out trying to call …
> Update Config to use importlib for defaults

- praw/models/reddit/comment.py
- praw/models/reddit/submission.py
Adds documentation for the `likes` attribute to `praw.models.Submission` and `praw.models.Comment` models.
There's no current open issue for this, although #726 was filed in 2017 that mentioned adding documentation for `Submission.likes` (among many other fields, some of which have been added already by other PRs, but `likes` hasn't). #208 is a related issue filed in 2013 by a user who wasn't yet aware of the `likes` attribute.
- https://github.com/reddit-archive/reddit/wiki/JSON#comment-implements-votable--created
- https://github.com/reddit-archive/reddit/wiki/JSON#link-implements-votable--created
- https://github.com/reddit-archive/reddit/wiki/JSON#votable-implementation
- https://www.reddit.com/r/redditdev/comments/2y26ty/praw_python_what_happened_to_the_likes_attribute/
- …
> docs: add `likes` attribute to Comment and Submission model doc comments

- docs/tutorials/refresh_token.rst
Performing the GET request for the scopes.json yields two additional scopes: `announcements` and `modnote`. The Scopes and their respective Description were added to the list.
This pull request provides an updated list of available OAuth2 Scopes.
https://www.reddit.com/api/v1/scopes.json
> Update list of Reddit OAuth2 Scopes
