praw/__init__.py

In [my efforts](https://github.com/reddit/reddit/commit/a82bc65192015e37276e8fe4e676f8042fd5fcbe) to make reddit's OAuth2 more [spec compliant](http://tools.ietf.org/html/rfc6749#section-3.3), I broke PRAW.

Fix #360. Interpret scopes as space-separated

---

praw/__init__.py

This is an attempted fix for [this issue I opened a little while ago](https://github.com/praw-dev/praw/issues/370).
I'm pretty inexperienced in open source and was unable to figure out how to run the test suite or how to use this version of praw instead of the default installed by pip, any help in the right direction and I'd be glad to verify that this fixes my issue, but this is a pretty simple change.

Adding 'hide_ads' to the input params of 'set_settings'

---

praw/__init__.py
praw/objects.py

Fix submission refresh parameters.

---

praw/__init__.py

Registering no longer requires a captcha, and creating a subreddit now
can require one.

Update captcha requirements

---

tests/__init__.py

Wrote a test for self posts with no body

Test for #380

---

praw/objects.py

Fix for #392

---

praw/objects.py

Pretty sure this is going to fail some tests - maybe someone can enlighten me on what goes wrong.

Added support for secondary stickies

---

praw/__init__.py

Resolve issue #485.

---

.gitignore
docs/pages/comment_parsing.rst
docs/pages/configuration_files.rst
docs/pages/contributor_guidelines.rst
docs/pages/faq.rst
docs/pages/getting_started.rst
praw/objects.py

Update various aspects of documentation. Sorry it took this long @bboe , I wasn't able to get to my pc.
Resolves: 
* #479 
* #475 
* Should resolve #413 (read the later comments)
* Undocumented issues regarding outdated info in docs.

Documentation Update

---

docs/pages/useful_scripts.rst

I wrote [`prawoauth2`](http://prawoauth2.readthedocs.org) which helps people writing Reddit bots/apps using OAuth2 super easy and simple. Since it's more like a tool for praw (and not a reddit bot), I have added it next to `PRAW Tools` in list.
And I also added [Goodreads Bot](https://github.com/avinassh/Reddit-GoodReads-Bot).
:beers:

Add `prawoauth2` and `Goodreads Bot`

---

docs/pages/oauth.rst

Brought to my attention by /u/avinassh. I think this is a good place to add it in.

Mention token autorefresh in oauth docs

---

docs/pages/useful_scripts.rst

My bot shifted in name, focus and usability. I wanted to reflect that, since it gets a share amount of views from PRAWs rtd.

Updated RedditRovers description (from MassdropBot)

---

praw/objects.py

Took first step in addressing comments[0] index error with refresh method by adding to documentation.

Added error to documentation of refresh(self)

---

praw/__init__.py

This adds support for suggested_comment_sort in the set_settings() method.

adding support for suggested_comment_sort

---

praw/multiprocess.py

Simple, retval = e instead of except Exception as retval.

Partially fix the praw multiprocess issues

---

docs/pages/call_and_response_bot.rst

Pull request to add the tutorial was submitted prematurely. Mostly minor copyedits, some changes to the presented code.

Clean up "Call and Response Bot" tutorial

---

CHANGES.rst
praw/__init__.py
praw/objects.py
tests/cassettes/test_get_rules.json
tests/test_unauthenticated_reddit.py

Nothing more complicated than it says in the title. Subreddits can now set official rules (not just by editing the sidebar), and this lets you retrieve them as a JSON dictionary.

Add method get_rules for a subreddit's rules

---

CHANGES.rst
README.rst
docs/index.rst
docs/pages/call_and_response_bot.rst
docs/pages/code_overview.rst
docs/pages/comment_parsing.rst
docs/pages/configuration_files.rst
docs/pages/contributor_guidelines.rst
docs/pages/faq.rst
docs/pages/getting_started.rst
praw/reddit.py

And other minor documentation fixes.

Update README.rst with PRAW4 content.

---

docs/pages/Comment extraction and parsing.rst

Added rst file for comment extraction and parsing

Added comment extraction and parsing

---

setup.py

I want to be a bit more flexible now on what prawcore version is
allowed. semversion allows backword breaking changes in an pre 1.0
release. However, I will commit to bumping prawcore's minor version if any
backwards incompatible changes are made.

Depend on prawcore >=0.0.15 <0.1.

---

praw/config.py
praw/reddit.py
tests/unit/test_config.py
tests/unit/test_reddit.py

Use simple Authorizer when refresh_token is provided in some cases.

---

praw/reddit.py
tests/unit/test_reddit.py

Address #610 and the comments
for commit 209b6e506b3c3b0e33d697542d114f6bb51a5e5b.
Also move update_checker module to extras_require

make update_checker an optional dependency

---

AUTHORS.rst
docs/pages/getting_started.rst

Add prerequisites and the most common tasks.

New content for get started doc

---

docs/pages/useful_scripts.rst

Added project chattR to useful_scripts.rst

---

AUTHORS.rst
CHANGES.rst
praw/const.py
praw/models/subreddits.py
tests/integration/cassettes/TestSubreddits.test_search_by_topic.json
tests/integration/models/test_subreddits.py

This feature provides ability to search matching subreddits by topic ([source code via reddit api](https://github.com/reddit/reddit/blob/master/r2/r2/controllers/api.py#L4730)). It's a fairly simple and straightforward query and implementation. I believe it matches well with the spirit / use cases of the library.
* [Feature Request discussion found on r/redditdev](https://www.reddit.com/r/redditdev/comments/46s39o/using_praw_to_find_subreddits_related_to_a_query/)
* [Reddit API Description for subreddits_by_topic query](https://www.reddit.com/dev/api/#GET_api_subreddits_by_topic)
I ran into trouble attempting to record my query with BetaMax. I would appreciate pointers on this, as I could not easily find how to add my local authentication via OS environ variables or a particular config …

Add search_by_topic for subreddits

---

docs/getting_started/authentication.rst

There was no issue (number) for this. Only includes documentation.

Update authentication.rst, include quotes

---

tox.ini

This PR resolves VersionConflict Error (caused by mismatch of dependency section between setup.py and tox.ini) which is thrown when running tox.

Update dependencies in tox.ini

---

CHANGES.rst
praw/models/reddit/subreddit.py
tests/integration/cassettes/TestSubredditFlair.test__call.json
tests/integration/cassettes/TestSubredditFlair.test__call_user_filter.json
tests/integration/models/reddit/test_subreddit.py

This makes SubredditFlair work like SubredditRelationship. Includes redditor
argument. Deprecates SubredditFlair.\_\_iter\_\_.
Fixes #693

Make SubredditFlair instances callable

---

docs/package_info/contributing.rst
praw/models/base.py

Fixes two small typos that I came across.

Fix two small typos

---

CHANGES.rst
praw/const.py
praw/models/reddit/subreddit.py
tests/integration/cassettes/TestSubreddit.test_rules.json
tests/integration/models/reddit/test_subreddit.py

Add Subreddit.rules to get subreddit rules

---

CHANGES.rst
praw/const.py
praw/models/reddit/live.py
tests/integration/cassettes/TestLiveContributorRelationship_test_invite__already_invited.json
tests/integration/cassettes/TestLiveContributorRelationship_test_invite__empty_list.json
tests/integration/cassettes/TestLiveContributorRelationship_test_invite__limited.json
tests/integration/cassettes/TestLiveContributorRelationship_test_invite__none.json
tests/integration/cassettes/TestLiveContributorRelationship_test_invite__redditor.json
tests/integration/cassettes/TestLiveContributorRelationship_test_remove_invite__fullname.json
tests/integration/cassettes/TestLiveContributorRelationship_test_remove_invite__redditor.json
tests/integration/models/reddit/test_live.py

This feature provides interfaces to send/remove live thread contributor invitation.
* #676
* https://www.reddit.com/dev/api/#POST_api_live_{thread}_invite_contributor
* https://www.reddit.com/dev/api/#POST_api_live_{thread}_rm_contributor_invite

Add invite() and remove_invite() to LiveContributorRelationship

---

CHANGES.rst
praw/const.py
praw/models/reddit/live.py
tests/integration/cassettes/TestLiveContributorRelationship_test_leave.json
tests/integration/models/reddit/test_live.py

This feature provides interface to abdicate live thread contributor position.
* #676
* https://www.reddit.com/dev/api#POST_api_live_{thread}_leave_contributor

Add LiveContributorRelationship.leave()

---

CHANGES.rst
praw/const.py
praw/models/reddit/live.py
tests/integration/cassettes/TestLiveContributorRelationship_test_remove__fullname.json
tests/integration/cassettes/TestLiveContributorRelationship_test_remove__redditor.json
tests/integration/models/reddit/test_live.py

This feature provides interface to `POST /api/live/thread/rm_contributor` which removes the redditor from the live thread contributors.
* https://github.com/praw-dev/praw/issues/676
* https://www.reddit.com/dev/api#POST_api_live_{thread}_rm_contributor

Add LiveContributorRelationship.remove()

---

CHANGES.rst
docs/code_overview/other.rst
docs/code_overview/other/livethreadcontribution.rst
praw/const.py
praw/models/reddit/live.py
tests/integration/cassettes/TestLiveThreadContrib_add.json
tests/integration/models/reddit/test_live.py
tests/unit/models/reddit/test_live.py

This feature provides intaface to POST /api/live/thread/update which adds an update to the live thread.
* https://www.reddit.com/dev/api#POST_api_live_%7Bthread%7D_update
* https://github.com/nmtake/praw/commit/e147a37#commitcomment-19895733 - API design discussion

Add `LiveThreadContribution.add()` and `LiveThread.contrib`

---

praw/const.py
praw/models/reddit/base.py
praw/models/reddit/live.py
tests/integration/cassettes/TestLiveThreadContribution.test_update__full_settings.json
tests/integration/cassettes/TestLiveThreadContribution.test_update__other_settings.json
tests/integration/cassettes/TestLiveThreadContribution.test_update__partial_settings.json
tests/integration/models/reddit/test_live.py
tests/unit/models/reddit/test_live.py
tox.ini

This feature provides interface to `POST /api/live/thread/edit` which updates a live thread's settings.
* https://www.reddit.com/dev/api#POST_api_live_{thread}_edit

Add LiveThreadContribution.update to edit a live thread settings

---

praw/models/reddit/live.py
praw/models/reddit/subreddit.py

Add usages to reddit live methods.  Concerns: I am a bit unsure articles (a/the/no articles) are correctly used.

Add usages to reddit live methods

---

CHANGES.rst
praw/const.py
praw/models/reddit/live.py
tests/integration/cassettes/TestLiveThread_test_report.json
tests/integration/models/reddit/test_live.py

This feature provides interface to `POST /api/live/:thread/report` to report the thread violating the reddit rules.
* https://www.reddit.com/dev/api#POST_api_live_{thread}_report

Add LiveThread.report

---

AUTHORS.rst
praw/models/reddit/mixins/messageable.py
praw/models/reddit/subreddit.py

Updated the documentation for sending messages and provided an additional example to send a message from a subreddit.
Also added documentation for getting moderator mail as well as replies to moderator mail messages.

Updated documentation for messages.

---

praw/models/reddit/subreddit.py
praw/models/reddit/wikipage.py

I updated a lot of documentation mostly surrounding wiki pages and moderation queues such as /about/modqueue, /about/log, /about/reports, etc.
Also fixed code example for removing a moderator from a subreddit.

Updated a lot of documentation

---

praw/models/reddit/subreddit.py

should be ban_reason, not reason. see:
https://www.reddit.com/dev/api/#POST_api_friend
Fixes #742

Fix argument name for ban reason in example

---

praw/models/reddit/wikipage.py
tests/integration/cassettes/TestWikiPage.test_init__with_revision__author_deleted.json
tests/integration/cassettes/TestWikiPage.test_revisions__author_deleted.json
tests/integration/models/reddit/test_wikipage.py

Fix crashes on wiki revisions with deleted author

---

CHANGES.rst

Adds changelog entry for #748 
Fixes #746

Add changelog entry for WikiPage revision bugfix

---

docs/code_overview/models/modmailconversation.rst
docs/code_overview/other.rst
docs/code_overview/other/modmail.rst
docs/code_overview/praw_models.rst
praw/const.py
praw/models/__init__.py
praw/models/reddit/modmail.py
praw/models/reddit/subreddit.py
praw/objector.py
praw/reddit.py
tests/integration/cassettes/TestSubredditModmail.test_call.json
tests/integration/models/reddit/test_subreddit.py

This provides the basic features that bboe mentioned in #740. I've tried to leave out the parsing while making minimal changes to the surrounding code; let me know if I should include more or less.
I included a test, but it's really just a stub at this point as the test doesn't actually fetch anything.

Add barebones support for fetching a modmail conversation

---

AUTHORS.rst
docs/examples/obtain_refresh_token.py
docs/tutorials/refresh_token.rst

Make it more interactive and fix a few bugs
The current script doesn't always flush the output of the url print command before entering the receive connection command. It's also slightly confusing for amateur users where to get the client id and secret and where to put them in the script.

Update the obtain oauth token script

---

praw/models/reddit/base.py
praw/models/reddit/modmail.py
praw/models/reddit/subreddit.py
tests/integration/cassettes/TestSubredditModmail.test_call__mark_read.json
tests/integration/models/reddit/test_subreddit.py

Fixes #764 
This also tweaks `RedditBase._fetch` in the manner we discussed, in case this pattern is useful in the future.

Add mark_read parameter to Modmail.__call__

---

praw/models/reddit/modmail.py
tests/unit/models/reddit/test_modmail.py

Add parameter check for ModmailConversation

---

CHANGES.rst
praw/models/reddit/subreddit.py
praw/objector.py
tests/integration/cassettes/TestSubredditModmail.test_create.json
tests/integration/models/reddit/test_subreddit.py
tests/unit/models/reddit/test_subreddit.py

Partially implements #703 
This adds the ability to create new modmail conversations.

Add Modmail.create

---

praw/models/reddit/modmail.py
praw/models/reddit/subreddit.py

This adds examples to the new modmail methods that were missing them.

Added missing examples to new modmail docstrings

---

CHANGES.rst
praw/const.py
praw/models/reddit/subreddit.py
tests/integration/cassettes/TestSubredditModmail.test_bulk_read.json
tests/integration/cassettes/TestSubredditModmail.test_subreddits.json
tests/integration/cassettes/TestSubredditModmail.test_unread_count.json
tests/integration/models/reddit/test_subreddit.py

Partially implements #703 (provide issue number of applicable)
This adds support for a few more new modmail features: bulk read, unread count, and subreddit listing.
Once this is merged, all the features provided by the new modmail API should be supported by PRAW. 🎉🎉🎉

Remaining modmail endpoints

---

docs/conf.py
docs/getting_started/logging.rst
docs/getting_started/multiple_instances.rst
docs/index.rst
setup.py

Doc additions

---

praw/models/reddit/subreddit.py

This should cover all the things on the present checklist at #797. If there are other things that should be included, perhaps I can add them to this PR and close that issue.

Add examples for new modmail

---

CHANGES.rst
praw/const.py
praw/models/reddit/mixins/__init__.py
praw/models/reddit/mixins/inboxtoggleable.py
tests/integration/cassettes/TestComment.test_disable_inbox_replies.json
tests/integration/cassettes/TestComment.test_enable_inbox_replies.json
tests/integration/cassettes/TestSubmission.test_disable_inbox_replies.json
tests/integration/cassettes/TestSubmission.test_enable_inbox_replies.json
tests/integration/models/reddit/test_comment.py
tests/integration/models/reddit/test_submission.py

Fixes #800.
I added an `InboxToggleableMixin` for this, but that's a horrible name and I'd welcome a better suggestion.

Enable toggling inbox replies on comments and submissions

---

CHANGES.rst
praw/models/reddit/live.py
tests/unit/models/reddit/test_live.py

Fix accessing LiveUpdate.contrib raises AttributeError

---

tests/integration/cassettes/TestReddit.test_live_now__featured.json
tests/integration/test_reddit.py

Quote from #733 which I wrote:
> This commit doesn't contain test for 200 OK (the endpoint returns 200 if there is a featured live thread, 204 no content if there is no featured). So the test for latter should be added in the future.
Here is the test for the 200 (featured live thread exists).

Add test for reddit.live.now() in the presence of featured live thread exists

---

CHANGES.rst
praw/models/reddit/subreddit.py
tests/integration/cassettes/TestSubreddit.test_submit__flair.json
tests/integration/models/reddit/test_subreddit.py

Add flair parameters to Subreddit.submit

---

praw/models/listing/mixins/redditor.py
praw/models/reddit/subreddit.py
praw/reddit.py

This PR collects various quibbles with the documentation that I've come across. Some are just little grammar tweaks. I also fixed a broken example and changed a docstring that referred to the wrong class.

Various small corrections to documentation

---

CHANGES.rst

Fix mistake in changelog

---

CHANGES.rst
praw/models/reddit/subreddit.py
tests/integration/cassettes/TestSubredditStylesheet.test_upload__invalid_ext.json
tests/integration/models/reddit/test_subreddit.py

Source of bug: https://www.reddit.com/r/redditdev/comments/6nnj1s/praw_bug_uploading_images_to_stylesheet/

Handle BAD_CSS_NAME when uploading stylesheet images

---

CHANGES.rst
praw/models/reddit/comment.py
tests/integration/cassettes/TestComment.test_refresh__raises_exception.json
tests/integration/models/reddit/test_comment.py

Removes the the bug listed in #838, but now results in ClientException instead
of unexpected behavior.

Raise ClientException on Comment.refresh if comment is not in tree

---

docs/tutorials/comments.rst

Small change in writing

---

AUTHORS.rst
CHANGES.rst
praw/models/reddit/subreddit.py

subreddit.submissions() sometimes returns a submission more than once. Found this bug while dumping reddit data into a db.

Fix subreddit.submissions duplication

---

praw/models/reddit/subreddit.py

If I've understood the scope of the issue correctly, this fixes #864. The issue with the setting being reset appears to already have been fixed by a change on Reddit's end, but this documents the new setting.

Add parameter allow_post_crosspost for subreddit settings

---

tests/integration/models/test_auth.py
tests/unit/test_config.py
tests/unit/test_reddit.py

Pass tests even if the DEFAULT config is set

---

.travis.yml

Simplify .travis.yml now that we no longer test on 3.3

---

praw/models/reddit/emoji.py
tests/integration/cassettes/TestEmoji.test__fetch__invalid_emoji.json
tests/integration/models/reddit/test_emoji.py
tests/unit/models/reddit/test_emoji.py

Fixes #904 
This allows Emoji to be treated case sensitively, per current Reddit spec. Also treats two emoji from the same name and different subreddits differently, per spec.

Case Sensitivity

---

docs/_static/theme_override.css
docs/conf.py
praw/models/reddit/subreddit.py

Related to #917. Like #920 but doesn't ruin the styling on ReadTheDocs.

Document common Subreddit attributes

---

praw/models/reddit/comment.py

Added an example to the CommentModeration class definition to appear on RTD.
RE:  https://www.reddit.com/r/redditdev/comments/8dmv8z/is_there_no_distinguish_method_for_comments_in/dxon2rd/
This is my first praw edit so let me know if this is incorrect. I'm u/theonefoster on reddit. 
I also don't know of a way to test this commit to make sure it formats correctly when published so this code is untested.

Add example code to CommentModeration class definition

---

CHANGES.rst
praw/models/util.py
praw/objector.py
tests/integration/models/reddit/test_subreddit.py

Add skip_existing parameter to stream_generator

---

praw/models/reddit/subreddit.py
praw/objector.py

- Alphabetized Subreddit properties
- Removed unnecessary parentheses in `objector.py`.

Minor style fixes

---

.github/CONTRIBUTING.md
praw/models/inbox.py

None
Was browsing the code and this struck my eye. Flagged it as insignificant and scrolled past but it kept bugging me. I hope it's not too much of a bother :)
a correct spelling
None

Minor Typographical Fix

---

docs/generate_local_docs.bat
praw/models/listing/mixins/submission.py
praw/models/reddit/comment.py
praw/models/reddit/mixins/editable.py
praw/models/reddit/mixins/gildable.py
praw/models/reddit/mixins/inboxable.py
praw/models/reddit/mixins/inboxtoggleable.py
praw/models/reddit/mixins/replyable.py
praw/models/reddit/mixins/reportable.py
praw/models/reddit/mixins/savable.py
praw/models/reddit/mixins/votable.py
praw/models/reddit/submission.py

Comment and Submission objects are now fully documented with examples (Mixins updated)
* Examples added to documentation

Added further examples to docs

---

CHANGES.rst
docs/code_overview/other/util.rst
praw/models/inbox.py
praw/models/reddit/redditor.py
praw/models/reddit/subreddit.py
praw/models/subreddits.py

Use sphinx's func instead of meth for non-class methods

---

docs/getting_started/quick_start.rst

Add warning to quick start about praw.ini files

---

CHANGES.rst
docs/code_overview/other.rst
docs/code_overview/other/trophy.rst
praw/config.py
praw/const.py
praw/models/__init__.py
praw/models/list/trophy.py
praw/models/reddit/redditor.py
praw/models/trophy.py
praw/praw.ini
praw/reddit.py
tests/integration/cassettes/TestRedditor.test_trophies.json
tests/integration/cassettes/TestRedditor.test_trophies__user_not_exist.json
tests/integration/models/reddit/test_redditor.py
tests/unit/models/test_trophy.py

Add Redditor.trophies()

---

praw/models/reddit/submission.py

Add docs to Submission.mark_visited()

---

AUTHORS.rst
CHANGES.rst
praw/models/reddit/comment.py
tests/integration/cassettes/TestComment.test_refresh__with_reply_sort_and_limit.json
tests/integration/models/reddit/test_comment.py

This feature provides the ability to choose the sort order and limit for comment replies.
* https://www.reddit.com/r/redditdev/comments/ac2x4d/praw_is_there_a_way_to_sort_comment_replies_by_new/

Add comment attributes reply_sort and reply_limit

---

CHANGES.rst
praw/models/reddit/widgets.py
tests/integration/cassettes/TestImageWidget.test_create_and_update_and_delete.json
tests/integration/cassettes/TestSubredditWidgetsModeration.test_upload_image.json
tests/integration/models/reddit/test_widgets.py

This feature provides support for creating `ImageWidget`s, as well as for uploading images, which is necessary to create an `ImageWidget`. It also includes minor improvements to the docstrings of the methods in `SubredditWidgetsModeration`.

Support uploading images and creating ImageWidgets

---

CHANGES.rst
praw/models/reddit/widgets.py
tests/integration/cassettes/TestCustomWidget.test_create_and_update_and_delete.json
tests/integration/cassettes/TestSubredditWidgetsModeration.test_upload_image.json
tests/integration/models/reddit/test_widgets.py

Works towards #941. This PR should only be merged once #990 is merged.
This feature provides support for creating `CustomWidget`s. It also adds a custom JSON serializer to handle `RedditBase` objects related to widgets, such as `ImageData`.

Support creating CustomWidgets

---

CHANGES.rst
praw/models/reddit/widgets.py
tests/integration/cassettes/TestMenu.test_create_and_update_and_delete.json
tests/integration/models/reddit/test_widgets.py

This feature provides support for creating `Menu` widgets.
Note: This PR should be merged after #993. Some of the commits in this PR are supposed to be merged in that commit, but since it hasn't been merged yet and this branch is based on that branch, they show up as part of this PR.

Support creating Menus

---

CHANGES.rst
praw/models/reddit/widgets.py
tests/integration/cassettes/TestButtonWidget.test_create_and_update_and_delete.json
tests/integration/models/reddit/test_widgets.py

This feature provides support for creating `ButtonWidget`s with the method `add_button_widget()`
Note: This PR should be merged after #993 and #994. Some of the commits in this PR are supposed to be merged in those commits, but since they haven't been merged yet and this branch is based on that branch, they show up as part of this PR.

Support creating ButtonWidgets

---

praw/models/reddit/widgets.py
tests/integration/cassettes/TestIDCard.test_update.json
tests/integration/cassettes/TestModeratorsWidget.test_update.json
tests/integration/cassettes/TestRulesWidget.test_update.json
tests/integration/models/reddit/test_widgets.py

This feature fixes a bug where the `ModeratorsWidget` and `RulesWidget` would complain about a missing attribute.
Reddit responds to widget update requests for moderator widgets and rules widgets without their `CHILD_ATTRIBUTE` field (`'mods'` and `'data'`, respectively). This PR fixes this in the `__init__` methods by initializing an empty list if the necessary attribute is missing. It also adds tests for updating `IDCard`,  `ModeratorsWidget`, and `RulesWidget`. These tests would have caught the issue if they had been written previously.
This is **#1000**! 😃🥳🎉

Fix Widget "No Attribute" Error

---

AUTHORS.rst
praw/models/reddit/submission.py

Here's the PR that @jarhill0 told me to create.
It adds a warning to the crosspost documentation.
I hope I've done this right.
This feature provides ... a warning added to the crosspost documentation.

Added crosspost warning

---

AUTHORS.rst
CHANGES.rst
praw/const.py
praw/models/reddit/subreddit.py
tests/integration/cassettes/TestSubredditStylesheet.test_delete_banner.json
tests/integration/cassettes/TestSubredditStylesheet.test_delete_banner_additional_image.json
tests/integration/cassettes/TestSubredditStylesheet.test_delete_banner_hover_image.json
tests/integration/cassettes/TestSubredditStylesheet.test_upload_banner__jpg.json
tests/integration/cassettes/TestSubredditStylesheet.test_upload_banner__png.json
tests/integration/cassettes/TestSubredditStylesheet.test_upload_banner_additional_image__jpg.json
tests/integration/cassettes/TestSubredditStylesheet.test_upload_banner_additional_image__png.json
tests/integration/cassettes/TestSubredditStylesheet.test_upload_banner_hover_image__jpg.json
tests/integration/cassettes/TestSubredditStylesheet.test_upload_banner_hover_image__png.json
tests/integration/models/reddit/test_subreddit.py

Fixes # 1027
This change provides upload and delete functions for the 3 new banner image types (banner image, additional banner image, and hover image) from the Reddit redesign.

Add support for Reddit Redesign banner images

---

praw/models/reddit/redditor.py
praw/models/reddit/submission.py
praw/models/reddit/subreddit.py

Helps with #917
Add more common attributes of Subreddit, Submission, and Redditor
I stared at a lot of JSON for this :)

More attributes

---

CHANGES.rst
praw/models/reddit/subreddit.py
pre_push.py
pyproject.toml
tests/integration/cassettes/TestSubreddit.test_random__returns_none.json
tests/integration/models/reddit/test_subreddit.py

Return None from subreddit.random when necessary

---

AUTHORS.rst
CHANGES.rst
praw/models/util.py

Cleanup of #1048

---

praw/models/reddit/subreddit.py

Fix error in reports example code

---

AUTHORS.rst

Thanks for all the great work!

Remove voussoir as a maintainer they're no longer an active contributor

---

praw/const.py

Bump PRAW version to 6.2.1dev0

---

praw/models/listing/mixins/redditor.py
praw/models/listing/mixins/subreddit.py
praw/models/reddit/comment.py
praw/models/reddit/live.py
praw/models/reddit/multi.py
praw/models/reddit/redditor.py
praw/models/reddit/submission.py
praw/models/reddit/subreddit.py
praw/models/reddit/widgets.py
praw/models/reddit/wikipage.py
praw/models/user.py
praw/util/__init__.py
praw/util/cache.py
tests/unit/util/test_cache.py

Features:
- Cleaned up constructors by eliminating a bunch of property-related variable assignments (e.g., `self._mod = None`).
- Made property logic simpler and more self contained.
- Property access is about 3x faster (using timeit over 1000000 trials) due to abolished `None` check.

Add `@cachedproperty` decorator

---

AUTHORS.rst
CHANGES.rst
praw/models/reddit/comment.py
praw/models/reddit/live.py
praw/models/reddit/message.py
praw/models/reddit/mixins/fullname.py
praw/models/reddit/modmail.py
praw/models/reddit/redditor.py
praw/models/reddit/submission.py
praw/models/reddit/subreddit.py
praw/objector.py
praw/reddit.py
praw/util/__init__.py
tests/unit/test_objector.py
tests/unit/util/test_util.py

I want to gradually clean up the Objector class.
It’s important that the keys of `self.parsers` are made internal constants as this will help to simplify things later on. Right now the `Objector.kind()` method is in the way of my clean up efforts and it needs to go.
Because `Objector.kind()` is only used by `.fullname` of `FullnameMixin` I’ve added the class member “`kind`” to only those with the mixin.

Objector changes

---

AUTHORS.rst
CHANGES.rst
docs/code_overview/other.rst
docs/code_overview/other/thingmoderationmixin.rst
praw/models/reddit/mixins/__init__.py
praw/models/reddit/submission.py
tests/integration/cassettes/TestCommentModeration.test_lock.json
tests/integration/cassettes/TestCommentModeration.test_unlock.json
tests/integration/models/reddit/test_comment.py

Finish off #1074

---

praw/models/reddit/subreddit.py

Closes #1071.
It just requires a documentation change, turns out.

Subreddit restrictions

---

CHANGES.rst
praw/models/reddit/subreddit.py
tests/integration/cassettes/TestSubredditStylesheet.test_upload_banner_additional_image__align.json
tests/integration/models/reddit/test_subreddit.py
tests/unit/models/reddit/test_subreddit.py

Add `align` parameter to SubredditStylesheet.upload_banner_additional_image()

---

CHANGES.rst
praw/const.py

Also includes an edit of the changelog ("Changed" -> "Removed").

Bump to 6.3.1

---

CHANGES.rst
praw/models/reddit/submission.py
tests/integration/cassettes/TestSubmission.test_crosspost__flair.json
tests/integration/cassettes/TestSubmission.test_crosspost__nsfw.json
tests/integration/cassettes/TestSubmission.test_crosspost__spoiler.json
tests/integration/models/reddit/test_submission.py

Added `flair_id`, `flair_text`, `nsfw` and `spoiler` to crosspost method of the submission class

added parameters to crosspost method

---

AUTHORS.rst
praw/models/reddit/subreddit.py

Fix docstrings of SubredditWiki class

---

.travis.yml

This reverts commit fa5013b40cfad39190ae72c05e88aeaf978d1b7d.

Revert "Temp-fix travis config by limiting pydocstyle version."

---

praw/models/reddit/mixins/replyable.py
tests/integration/cassettes/TestComment.test_reply__none.json
tests/integration/cassettes/TestSubmission.test_reply__none.json
tests/integration/models/reddit/test_comment.py
tests/integration/models/reddit/test_message.py
tests/integration/models/reddit/test_submission.py

Closes #1093.
@Watchful1 has uncovered a scenario where reddit doesn’t return a comment object after replying to a comment in a quarantined subreddit.
I propose that `.reply()` should return `None` in this case.
Please see the linked issue to view the full discussion and the other candidate solutions.

Make `.reply()` return `None` when reddit doesn’t return a comment object

---

praw/models/reddit/mixins/__init__.py
praw/models/reddit/mixins/editable.py
praw/models/reddit/mixins/gildable.py
praw/models/reddit/mixins/messageable.py
praw/models/reddit/mixins/replyable.py
praw/models/reddit/mixins/reportable.py
praw/models/reddit/mixins/savable.py
praw/models/reddit/subreddit.py

A number of documentation and style updates to the `mixins` classes, including properly linking to `Comment` and `Submission` classes, correcting a few typos and outdated features (Reddit Gold is [no more](https://www.reddit.com/coins)), and also documenting an API limitation of `report()` (reports longer than 100 characters cause an `APIException`.)
There is also a small typo fix for `praw/models/reddit/subreddit.py` that was introduced with #1125.

Cleaning up models/reddit/mixins

---

.github/CONTRIBUTING.md

Sphinx is needed but not mentioned in the CONTRIBUTING.md file. This is a trivial change.

Add sphinx requirement

---

praw/exceptions.py
praw/models/front.py
praw/models/list/base.py
praw/models/listing/domain.py
praw/models/listing/generator.py
praw/models/listing/listing.py
praw/models/listing/mixins/redditor.py
praw/models/listing/mixins/subreddit.py
praw/models/reddit/base.py
praw/models/reddit/collections.py
praw/models/reddit/comment.py
praw/models/reddit/emoji.py
praw/models/reddit/live.py
praw/models/reddit/message.py
praw/models/reddit/modmail.py
praw/models/reddit/more.py
praw/models/reddit/multi.py
praw/models/reddit/redditor.py
praw/models/reddit/removal_reasons.py
praw/models/reddit/submission.py
praw/models/reddit/subreddit.py
praw/models/reddit/widgets.py
praw/models/reddit/wikipage.py
praw/models/trophy.py
praw/models/user.py
tests/integration/models/reddit/test_more.py
tests/integration/models/test_comment_forest.py

- #1165 
This feature removes useless code that makes it easier to read and understand the code

Reove useless super call arguments

---

praw/models/front.py
praw/models/inbox.py
praw/models/listing/mixins/base.py
praw/models/listing/mixins/gilded.py
praw/models/listing/mixins/redditor.py
praw/models/listing/mixins/rising.py
praw/models/listing/mixins/submission.py
praw/models/listing/mixins/subreddit.py
praw/models/reddit/live.py
praw/models/reddit/subreddit.py
praw/models/reddit/wikipage.py
praw/models/redditors.py
praw/models/subreddits.py
praw/models/user.py

- #1163 
This feature adds disclaimers to the docstring.

Add listing generator disclaimer docstrings

---

praw/models/reddit/multi.py

Corrects typos where Multireddits are called Subreddits

Correct minor typos

---

CHANGES.rst

#1161: Provides changelog entry announcing removal

Announce expected changes

---

praw/objector.py

Remove NoReturn

---

praw/models/reddit/collections.py

#1164 
-> ./praw/models/reddit/colections.py

(#1164) Add types to reddit/collections.py

---

praw/models/base.py

#1164 
-> ./praw/models/base.py

(#1164) Type annotate base.py

---

praw/models/user.py

#1164 
-> ./praw/models/user.py

(#1164) Add types for user.py

---

praw/models/reddit/live.py

#1164 
-> ./praw/models/reddit/live.py

(#1164) Add types to reddit/live.py

---

praw/models/reddit/emoji.py

#1164 
-> ./praw/models/reddit/emoji.py

(#1164) Add types to reddit/emoji.py

---

praw/models/reddit/message.py

#1164
-> ./praw/models/reddit/message.py

(#1164) Add types to reddit/message.py

---

praw/models/reddit/modmail.py

#1164 
-> ./praw/models/reddit/modmail.py

(#1164) Add types to reddit/modmail.py

---

praw/models/listing/mixins/gilded.py

#1164 
-> ./praw/models/listing/mixins/gilded.py

(#1164) Add types to listing/mixins/gilded.py

---

praw/models/front.py

#1164 
-> ./praw/models/front.py

(#1164) Add types to front.py

---

praw/models/helpers.py

#1164 
-> ./praw/models/helpers.py

(#1164) Add types to helpers.py

---

praw/models/mod_action.py

#1164 
-> ./praw/models/mod_action.py

(#1164) Add types to mod_action.py

---

praw/models/preferences.py

#1164 
-> ./praw/models/preferences.py

(#1164) Add types to preferences.py

---

praw/models/redditors.py

#1164 
-> ./praw/models/redditors.py

(#1164) Add types to redditors.py

---

praw/models/subreddits.py

#1164 
-> ./praw/models/subreddits.py

(#1164) Add types to subreddits.py

---

praw/models/trophy.py

#1164 
-> ./praw/models/trophy.py

(#1164) Add types to trophy.py

---

praw/models/util.py

#1164 
-> ./praw/models/util.py

(#1164) Add types to util.py

---

praw/models/list/base.py

#1164 
-> ./praw/models/list/base.py

(#1164) Add types to base.py

---

praw/models/listing/domain.py

#1164 
-> ./praw/models/listing/domain.py

(#1164) Add types to domain.py

---

praw/models/listing/listing.py

#1164 
-> ./praw/models/listing/listing.py

(#1164) Add types to listing.py

---

praw/models/listing/mixins/base.py

#1164
-> ./praw/models/listing/mixins/base.py

(#1164) Add types to listing/mixins/base.py

---

praw/models/listing/mixins/rising.py

#1164 
-> ./praw/models/listing/mixins/rising.py

(#1164) Add types to listing/mixins/rising.py

---

praw/models/listing/mixins/submission.py

#1164 
-> ./praw/models/listing/mixins/submission.py

(#1164) Add types to listing/mixins/submission.py

---

praw/models/reddit/base.py

#1164 
-> ./praw/models/reddit/base.py

(#1164) Add types to reddit/base.py

---

praw/models/reddit/comment.py

#1164 
-> ./praw/models/reddit/comment.py

(#1164) Add types to reddit/comment.py

---

praw/models/comment_forest.py

#1164 
-> ./praw/models/comment_forest.py

(#1164) Add types to comment_forest.py

---

praw/models/reddit/more.py

#1164 
-> ./praw/models/reddit/more.py

(#1164) Add types to reddit/more.py

---

praw/models/listing/generator.py

#1164 
-> ./praw/models/listing/generator.py

(#1164) Add types to generator.py

---

praw/models/reddit/multi.py

#1164 
-> ./praw/models/reddit/multi.py

(#1164) Add types to reddit/multi.py

---

praw/util/snake.py

#1164 
-> ./praw/util/snake.py

(#1164) Add types to util/snake.py

---

praw/models/reddit/submission.py

#1164 
-> ./praw/models/reddit/submission.py

(#1164) Add types to models/reddit/submission.py

---

docs/getting_started/authentication.rst
docs/getting_started/installation.rst
docs/getting_started/logging.rst
docs/getting_started/multiple_instances.rst
docs/getting_started/quick_start.rst
praw/reddit.py

Some standardization of styles in the "Getting Started" section of the documents and a couple of grammar fixes as well.
These fixes are also consistent with #1152.

Formatting Updates to "Getting Started"

---

tests/unit/models/reddit/test_widgets.py
tests/unit/util/test_cache.py

When running coverage tests saw that there was a bunch of code not ran so I made minor changes on the tests.

Minor unit test improvement

---

praw/models/reddit/subreddit.py

The argument redditor is required yet it has a default value of None, which it should not.

Remove =None for required arg

---

praw/models/base.py

PRAWBase takes None as an argument but that is not shown, so I updated that.

Fix for PRAWBase

---

CODE_OF_CONDUCT.md

Source: https://www.contributor-covenant.org/version/2/0/code_of_conduct.md

Replace Code of Conduct to version 2.0

---

.github/CONTRIBUTING.md
CHANGES.rst
README.rst

Replace gitter with slack

---

README.rst

Add downloads badge

---

praw/models/reddit/wikipage.py

Type wikipage.py

---

praw/models/reddit/subreddit.py
praw/models/reddit/wikipage.py

More replacements to code-block

Continue adding consistency

---

praw/models/__init__.py
praw/models/auth.py
praw/models/inbox.py
praw/models/listing/generator.py
praw/models/listing/mixins/subreddit.py
praw/models/modaction.py
praw/models/reddit/live.py
praw/models/reddit/mixins/__init__.py
praw/models/reddit/subreddit.py
praw/models/reddit/widgets.py
praw/models/redditors.py
praw/models/subreddits.py
praw/objector.py
praw/reddit.py

A python tool, isort, orders imports, and so I recursively ran it through the project

Import order with isort

---

setup.cfg

They should not be universal anymore.

Wheels are no longer universal

---

praw/models/reddit/mixins/__init__.py

Add documentation to fix #1115

Address #1115

---

AUTHORS.rst

1. Comment out the lines `- Add "Name <email (optional)> and github profile link" above this line.`
2. Add myself to documentation contributors
3. Reflect username change

Add commented lines & add myself to documentation

---

praw/exceptions.py

The new WebsocketException doesn't have type data for parameters, so I added them.

Type new exception

---

.github/workflows/ci.yml

Coveralls is spelled with 2 l's, not 1 l

Fix small typo

---

README.rst

Reflects the actual name of the Workflow.

Change name from Python Package to CI

---

praw/models/reddit/more.py
praw/objector.py

Fix #1282 .
This PR will contain a checklist with the addressed issues. The checklist in the issue is for fixes in master.

Deal with assert statements

---

praw/exceptions.py

Instantize (typo) -> Initialize

Change typo

---

AUTHORS.rst
CHANGES.rst
docs/getting_started/configuration/prawini.rst
praw/config.py
praw/const.py
praw/praw.ini
praw/reddit.py
tests/unit/praw.ini
tests/unit/test_config.py

This feature provides a new initialization argument to the Reddit class called 'interpolation' which takes the values 'basic' and 'extended' use it to configure ConfigParser.
By default interpolation remains disabled to maintain backwards compatibility.
* https://www.reddit.com/r/redditdev/comments/en8j9y/praw_using_interpolation_in_prawini/

Implementing configurable interpolation

---

praw/exceptions.py
praw/models/auth.py
praw/models/reddit/base.py
praw/models/reddit/comment.py
praw/models/reddit/submission.py
praw/reddit.py
tests/unit/test_exceptions.py

Makes exception classes for exceptions called more than once. Fix #1179 as  I realized invalid credentials are going to have to be handled on the prawcore level.

New exception types

---

praw/exceptions.py

Fix typo and add notice

---

README.rst

Add python versions badge

---

CHANGES.rst

Wrong year

---

README.rst

Use HTTPS links

---

praw/models/preferences.py

Fix #1299
will also try to sort other attribute lists as i find them

Sort location arguments

---

.github/workflows/ci.yml
pre_push.py

Add --keep-going argument

---

setup.py
tools/static_word_checks.py

Add more documentation info to the static check tool

---

praw/models/listing/mixins/gilded.py
praw/models/listing/mixins/rising.py
praw/models/reddit/mixins/replyable.py
praw/models/reddit/multi.py
praw/models/reddit/subreddit.py
praw/models/reddit/wikipage.py

Add code examples

---

praw/models/reddit/collections.py
praw/models/reddit/comment.py
praw/models/reddit/submission.py
praw/models/reddit/subreddit.py
praw/models/reddit/wikipage.py

Document cached properties

---

CHANGES.rst
praw/models/reddit/submission.py
tests/integration/cassettes/TestSubmissionModeration.test_flair_all.json
tests/integration/cassettes/TestSubmissionModeration.test_flair_just_css_class.json
tests/integration/cassettes/TestSubmissionModeration.test_flair_just_template_id.json
tests/integration/cassettes/TestSubmissionModeration.test_flair_text_and_css_class.json
tests/integration/cassettes/TestSubmissionModeration.test_flair_text_only.json
tests/integration/cassettes/TestSubmissionModeration.test_flair_with_template_id.json
tests/integration/models/reddit/test_submission.py

Fix #1177 
This feature provides a way to use template ids from SubmissionModeration.
* 
*

Sub mod flair

---

praw/models/reddit/subreddit.py
praw/models/user.py

Explains the return of a few methods.

Add note for methods

---

.github/workflows/ci.yml
pre_push.py
tools/check_documentation.py

~Fix #917~ (This one is already fixed and can be closed now.)
Fix #924 
Fix #1311 
This feature provides a tool to check for common attributes in every RedditBase subclass and code examples in every method of each subclass.

Check documentation for example attributes and code examples

---

AUTHORS.rst
CHANGES.rst
praw/endpoints.py
praw/models/reddit/emoji.py
tests/integration/cassettes/TestEmoji.test__fetch.json
tests/integration/cassettes/TestEmoji.test__fetch__invalid_emoji.json
tests/integration/cassettes/TestEmoji.test_update.json
tests/integration/cassettes/TestEmoji.test_update__with_preexisting_values.json
tests/integration/cassettes/TestSubredditEmoji.test__iter.json
tests/integration/cassettes/TestSubredditEmoji.test_add_with_perms.json
tests/integration/models/reddit/test_emoji.py
tests/unit/models/reddit/test_emoji.py

Added support for changing the emoji permissions when uploading, and also a new feature, to change/update the permissons of an existing emoji.
I don't know how to explain it better than that.
Fix #1129

Added emoji permission support

---

CHANGES.rst
praw/exceptions.py
praw/models/reddit/subreddit.py
tests/integration/cassettes/TestSubredditFlairTemplates.test_update.json
tests/integration/cassettes/TestSubredditFlairTemplates.test_update_false.json
tests/integration/cassettes/TestSubredditFlairTemplates.test_update_fetch.json
tests/integration/cassettes/TestSubredditFlairTemplates.test_update_fetch_no_css_class.json
tests/integration/cassettes/TestSubredditFlairTemplates.test_update_fetch_no_text.json
tests/integration/cassettes/TestSubredditFlairTemplates.test_update_fetch_no_text_or_css_class.json
tests/integration/cassettes/TestSubredditFlairTemplates.test_update_fetch_only.json
tests/integration/cassettes/TestSubredditFlairTemplates.test_update_invalid.json
tests/integration/models/reddit/test_subreddit.py
tests/unit/models/reddit/test_subreddit.py
tests/unit/test_exceptions.py

Fix #1139
Fix #1306 
Road to Merge:

Make SubredditFlairTemplates.update get previous flair information

---

README.rst

Update Slack link

---

CHANGES.rst
praw/endpoints.py
praw/models/reddit/subreddit.py
tests/integration/cassettes/TestSubreddit.test_post_requirements.json
tests/integration/models/reddit/test_subreddit.py

This addresses the new API changes found in https://www.reddit.com/r/redditdev/comments/ezz3td/upcoming_api_change_post_apisubmit/

New api endpoint

---

docs/getting_started/multiple_instances.rst

Supplement #1336 
These are errors that are mostly caused by reasons out of PRAW's control, but it would be useful to document them.

Doc change

---

docs/getting_started/faq.rst

Fix code rendering in FAQ

---

CHANGES.rst
praw/models/user.py
tests/integration/models/test_user.py

Removes as per the plan to remove on the next major release.

Remove moderator_subreddits as per deprecation plan

---

CHANGES.rst
docs/index.rst
docs/package_info/praw7_migration.rst
praw/exceptions.py
praw/models/reddit/live.py
praw/models/reddit/mixins/reportable.py
praw/models/reddit/subreddit.py
praw/objector.py
pytest.ini
tests/integration/models/reddit/test_live.py
tests/integration/models/reddit/test_subreddit.py
tests/integration/test_objector.py
tests/unit/test_deprecations.py
tests/unit/test_exceptions.py
tests/unit/test_objector.py

Fix #1339
Addresses #1341 and #1342
This feature provides a containerized solution to exceptions, as suggested by @Pyprohly 
* 
*

New exception

---

.flake8
CHANGES.rst
praw/models/reddit/mixins/__init__.py
praw/models/reddit/redditor.py
praw/models/user.py
praw/reddit.py
tests/integration/cassettes/TestCommentModeration.test_send_removal_message__error.json
tests/integration/models/reddit/test_comment.py
tests/integration/models/reddit/test_redditor.py
tests/integration/models/reddit/test_submission.py
tests/integration/models/test_user.py
tests/unit/test_reddit.py

Raise RedditAPIException instead of BadRequest

---

tests/unit/test_exceptions.py

Change exceptions to use `issubclass` which does not require instantiation

---

praw/models/reddit/emoji.py
praw/models/reddit/more.py
praw/models/reddit/wikipage.py
tests/unit/models/reddit/test_emoji.py
tests/unit/models/reddit/test_more.py

Make comparable with other

---

praw/models/trophy.py
tests/integration/cassettes/TestTrophy.test_equality.json
tests/integration/models/test_trophy.py
tests/unit/models/test_trophy.py

Make trophies comparable

---

praw/models/reddit/subreddit.py
tests/integration/cassettes/TestSubredditModeration.test_update.json
tests/integration/models/reddit/test_subreddit.py

Subreddit update

---

setup.py

Change sphinx to <3.0

---

AUTHORS.rst
praw/models/reddit/comment.py
praw/models/reddit/message.py
praw/models/redditors.py

Clarifying the format of ''parent_id''.

Comment clarification

---

.github/workflows/ci.yml

This helps debug where missing coverage is.

Add line numbers to any missed statements

---

docs/index.rst
docs/package_info/glossary.rst

There are a bunch of terms with vague meanings, so I decided to define them in the glossary.

Start a glossary

---

CHANGES.rst
docs/getting_started/configuration.rst
docs/getting_started/installation.rst
docs/package_info/contributing.rst
docs/tutorials/reply_bot.rst

The main premise of this PR was to fix dead url links. 
It also changed http links to https, and added an alternate installation method directly using Git.

Minor Documentation Improvements

---

docs/package_info/glossary.rst

Fix rendering typo

---

docs/package_info/contributing.rst

Add note to install the [dev] options

---

SECURITY.md

~Per #1412, we want support for PRAW5 included.~
Instead, change the language to not rely on a specific version.

Support PRAW5 per #1412

---

praw/models/reddit/mixins/editable.py
praw/models/reddit/mixins/fullname.py
praw/models/reddit/mixins/messageable.py
praw/models/reddit/mixins/replyable.py
praw/models/reddit/mixins/reportable.py
praw/models/reddit/mixins/savable.py
praw/models/reddit/mixins/votable.py

Type all mixins

---

praw/models/listing/mixins/submission.py
praw/models/reddit/collections.py
praw/models/reddit/mixins/__init__.py
praw/models/reddit/mixins/inboxable.py
praw/models/reddit/mixins/inboxtoggleable.py
praw/models/reddit/mixins/savable.py
praw/models/reddit/mixins/votable.py
praw/models/reddit/submission.py

This makes a box similar to the `note::` box.

Use seealso:: directive

---

praw/config.py
tests/unit/test_reddit.py

Convert timeout to int

---

CHANGES.rst
praw/config.py
praw/praw.ini
praw/reddit.py
tests/unit/models/test_redditors.py
tests/unit/test_reddit.py

Api ratelimit

---

docs/getting_started/quick_start.rst
docs/package_info/references.rst
docs/tutorials/comments.rst
praw/models/auth.py
praw/models/comment_forest.py
praw/models/helpers.py
praw/models/listing/mixins/base.py
praw/models/preferences.py
praw/models/reddit/emoji.py
praw/models/reddit/live.py
praw/models/reddit/mixins/__init__.py
praw/models/reddit/multi.py
praw/models/reddit/redditor.py
praw/models/reddit/removal_reasons.py
praw/models/reddit/submission.py
praw/models/reddit/subreddit.py
praw/models/reddit/widgets.py
praw/models/reddit/wikipage.py
praw/models/redditors.py
praw/models/subreddits.py
praw/models/trophy.py
praw/models/user.py
praw/reddit.py

WIP, will be mergeable once all files are inspected.

Fix multitude of typos

---

docs/getting_started/configuration/options.rst
setup.py

Now that bboe/update-checker#14 has been merged, we can change the documentation.

Change to report via stderr

---

docs/getting_started/faq.rst

Add FAQ entry about login

---

setup.py

Per python/typing#266, the issue was fixed in versions > 3.5.3.
Fix #1440

Set minimum python version to >3.5.3

---

praw/models/reddit/poll.py
praw/objector.py
tests/integration/models/reddit/test_poll.py

Per https://github.com/praw-dev/praw/pull/1460#discussion_r417594256 and https://github.com/praw-dev/praw/pull/1460#discussion_r417611241.

Rename PollData.get_option to PollData.option; use split rather than partition

---

docs/getting_started/logging.rst

Add new log data

---

tox.ini

The changes made in setup.py have not been moved to the tox.ini file

Add setup.py changes to tox.ini

---

CHANGES.rst
praw/reddit.py
tests/integration/cassettes/TestReddit.test_bare_badrequest.json
tests/integration/test_reddit.py

Ensure that BadRequests without detailed error data are raised as actual BadRequests

---

praw/models/reddit/rules.py

Minor improvements to Rules

---

docs/getting_started/configuration/environment_variables.rst

The indicated behavior was incorrect, and the documentation has been updated to reflect the true behavior.
Fix #1393
https://github.com/praw-dev/praw/blob/4d26d8b1b3a034554aa72e233dcc8932c6f1bc59/praw/config.py#L101-L108

Reword documentation

---

CHANGES.rst
README.rst
docs/getting_started/authentication.rst
docs/getting_started/configuration.rst
docs/getting_started/configuration/options.rst
docs/getting_started/configuration/prawini.rst
docs/getting_started/configuration/reddit_initialization.rst
docs/getting_started/logging.rst
docs/getting_started/quick_start.rst
docs/tutorials/comments.rst
docs/tutorials/reply_bot.rst
praw/models/comment_forest.py
praw/models/inbox.py
praw/models/listing/mixins/base.py
praw/models/listing/mixins/redditor.py
praw/models/reddit/collections.py
praw/models/reddit/comment.py
praw/models/reddit/live.py
praw/models/reddit/mixins/messageable.py
praw/models/reddit/subreddit.py
praw/models/reddit/widgets.py
praw/models/reddit/wikipage.py

Make more black-esque formatting changes

---

praw/models/reddit/subreddit.py

This parameter was undocumented. This change adds documentation of the parameter.

Document the `reason` parameter in SubredditStylesheet.update method

---

praw/models/reddit/multi.py
praw/models/reddit/subreddit.py

There were a few places that were calling `self._reddit.request("PUT", ...` that might as well just use the `Reddit.put()` method.

Use Reddit.put() instead of passing the HTTP method as a string

---

praw/models/reddit/rules.py
praw/models/reddit/subreddit.py
tests/integration/models/reddit/test_rules.py
tests/unit/test_deprecations.py

Apply post-merge code review suggestions and update documentation

---

docs/package_info/praw7_migration.rst
praw/exceptions.py
praw/reddit.py

Add deprecation directive

---

CHANGES.rst
praw/models/reddit/removal_reasons.py
tests/integration/cassettes/TestSubredditRemovalReasons.test_update_empty.json
tests/integration/models/reddit/test_removal_reasons.py
tests/unit/models/reddit/test_removal_reasons.py

Fix #1443 
This feature provides updated documentation and a retrieval method similar to the Rules class.

Update Removal Reasons

---

praw/models/reddit/subreddit.py

This is a formatting fix in the documentation of subreddit streams to use proper code formatting in Sphinx.

Fix a formatting error in the documentation of subreddit streams.

---

docs/getting_started/faq.rst

Also fixes formatting error in earlier entry
Fix #880
This feature provides a FAQ entry explaining how to do URL searches

Add FAQ entry per #880

---

praw/exceptions.py
praw/models/reddit/comment.py
praw/models/reddit/message.py
praw/models/reddit/redditor.py
praw/models/reddit/submission.py
praw/models/reddit/subreddit.py
praw/models/reddit/widgets.py
praw/reddit.py

Adds a cachedproperty to a method, also adds a few type hints

Fix uncached properties

---

CHANGES.rst
praw/exceptions.py
praw/models/reddit/subreddit.py
tests/unit/models/reddit/test_subreddit.py
tests/unit/test_deprecations.py
tests/unit/test_exceptions.py

Fix #1433 
* https://www.reddit.com/r/redditdev/comments/g7s1yx/praw_keyerror_redirect_when_trying_to_upload/foje7iz?utm_source=share&utm_medium=web2x

Raise exception when invalid media is used

---

tests/unit/models/reddit/test_subreddit.py

Apply black formatting

---

praw/const.py

Bump to 7.1.1.dev0

---

CHANGES.rst
praw/endpoints.py
praw/models/reddit/subreddit.py
tests/integration/cassettes/TestSubreddit.test_submit_gallery.json
tests/integration/cassettes/TestSubreddit.test_submit_gallery__flair.json
tests/integration/cassettes/TestSubreddit.test_submit_gallery_disabled.json
tests/integration/models/reddit/test_subreddit.py
tests/unit/models/reddit/test_subreddit.py

This feature adds support for submitting the new reddit galleries.

Add `submit_gallery` method

---

CHANGES.rst
praw/models/reddit/modmail.py
praw/reddit.py
tests/integration/cassettes/TestModmailConversation.test_mute_duration.json
tests/integration/models/reddit/test_modmail.py

This feature provides the ability to specify a mute duration.

Add ability to specify modmail mute duration

---

CHANGES.rst
praw/endpoints.py
praw/models/__init__.py
praw/models/listing/listing.py
praw/models/reddit/subreddit.py
praw/objector.py
praw/reddit.py
tests/integration/cassettes/TestSubredditRelationships.test_moderator_invited_moderators.json
tests/integration/models/reddit/test_subreddit.py

This feature provides the ability to get the list of invited moderators of a subreddit.

Add invited moderators endpoint

---

.github/workflows/ci.yml

This is to resolve the CI issues currently preventing other tests from running

Don't error sphinx on warnings

---

praw/praw.ini

Minor change that explains the setting better.

Make comment more descriptive

---

.github/workflows/ci.yml
setup.py

Add python 3.9 support

---

AUTHORS.rst
CHANGES.rst
praw/models/reddit/submission.py
tests/unit/models/reddit/test_submission.py

Fixes #1553
Simple fix raising the correct error in case of invalid submission URL

Submission URL error handling fix

---

AUTHORS.rst
CHANGES.rst
praw/reddit.py
tests/integration/cassettes/TestReddit.test_info_sr_names.json
tests/integration/test_reddit.py
tests/unit/test_reddit.py

This change adds the `sr_name` parameter as defined in the Reddit API documentation (https://www.reddit.com/dev/api#GET_api_info). This change was implemented in the Reddit API earlier today, which makes it easier for developers to get many subreddits at once by their name, which can significantly reduce the amount of requests made by an API client.
This change adds the parameter to info, updates relevant checks, and updates the test that test for IDs provided. Previously, if developers wanted to use this new parameter they would have to perform the request manually.
This feature provides a way for developers to use the `sr_name` parameter.
* https://www.reddit.com/dev/api#GET_api_info
* https://www.reddit.com/r/redditdev/comments/jfltfx/any_way_of_speeding_up_my_api_requests/g9le48w/
CC …

Adds the "sr_name" parameter to Reddit.info().

---

praw/models/reddit/subreddit.py

A small documentation update, regarding SubredditModeration.update parameters.
* https://www.reddit.com/dev/api#POST_api_site_admin
* https://www.reddit.com/r/redditdev/comments/itsj8m/praw_unable_to_change_subreddit_type_setting/

Update SubredditModeration.update documentation

---

praw/models/reddit/base.py
praw/models/reddit/collections.py
praw/models/reddit/comment.py
praw/models/reddit/live.py
praw/models/reddit/message.py
praw/models/reddit/modmail.py
praw/models/reddit/redditor.py
praw/models/reddit/removal_reasons.py
praw/models/reddit/rules.py
praw/models/reddit/submission.py
praw/models/reddit/subreddit.py
praw/models/reddit/wikipage.py
tests/unit/models/reddit/test_collections.py
tests/unit/models/reddit/test_comment.py
tests/unit/models/reddit/test_live.py
tests/unit/models/reddit/test_redditor.py
tests/unit/models/reddit/test_removal_reasons.py
tests/unit/models/reddit/test_rules.py
tests/unit/models/reddit/test_submission.py
tests/unit/models/reddit/test_subreddit.py
tests/unit/models/reddit/test_wikipage.py

Fixes #1552 
This feature provides a check for unset STR_FIELD attribute values. It also adds a few private parameters, which are mentioned in the commit for RedditBase.
* #1583 
* https://github.com/praw-dev/praw/pull/1583#issuecomment-729027347

Implement a check on RedditBase for unset STR_FIELD attribute values

---

CHANGES.rst

This adds a change log entry for #1563.

Add change log entry for #1563

---

AUTHORS.rst
praw/models/reddit/comment.py
praw/models/reddit/submission.py

Fixes #1602 
Added saved attribute to docs for comment and submission models

Add saved attribute to docs for comment and submission models

---

AUTHORS.rst
docs/tutorials/comments.rst

Fix grammar in documentation

---

docs/getting_started/authentication.rst

The client secret is a  30-character string .

Fix a value  in  authentication.rst 

---

tests/integration/cassettes/TestSubredditRelationships.test_moderator_invited_moderators__fetch_all.json
tests/integration/models/reddit/test_subreddit.py

This improves the existing test and adds an additional test for the invited moderators endpoint.

Add test case for invited moderators endpoint

---

CHANGES.rst
docs/getting_started/configuration/options.rst
docs/getting_started/multiple_instances.rst
praw/reddit.py
tests/unit/test_reddit.py

This PR catches things miss in #1628.
* #1628

Improve error message and documentation for asynchronous check and add change log entry for #1628

---

CHANGES.rst
praw/reddit.py

Skip checking for async if in a Jupyter notebook

---

.github/workflows/prepare_release.yml

Unfortunately this needs to be merged to master in order to even test
it. Fortunately, it doesnt affect our code at all, so here we go!

Set up workflow_dispatch workflow

---

praw/models/comment_forest.py
praw/models/reddit/mixins/inboxable.py
praw/models/reddit/redditor.py
praw/models/reddit/submission.py
praw/models/reddit/subreddit.py
praw/models/reddit/widgets.py
praw/reddit.py

This fixes a few more typos I found.

More typo fixes

---

.github/workflows/tag_release.yml
tools/extract_log_entry.py

Extract change log for releases

---

setup.py

This adds more urls to the PyPI page

Add project urls

---

docs/code_overview/other.rst
docs/code_overview/other/mod_action.rst
praw/models/mod_action.py

This adds the ModAction class to the docs.

Add the ModAction class to the docs

---

.github/workflows/ci.yml

- https://github.com/praw-dev/praw/pull/1682/checks?check_run_id=1922801456#step:1:30

Fix complete_coveralls action

---

docs/code_overview/other.rst
docs/code_overview/other/stylesheet.rst

This adds the Stylesheet class to the docs.

Add the Stylesheet class to the docs

---

praw/models/reddit/subreddit.py

Fixes #1631 
This adds a method to update old reddit settings like `description`

Add method to update settings on old reddit

---

CHANGES.rst
praw/exceptions.py
praw/models/user.py
tests/unit/models/test_user.py
tests/unit/test_deprecations.py

Deprecate user.me() returning None

---

praw/models/reddit/comment.py

Fix typo in comment.show docs

---

praw/models/mod_action.py
praw/models/reddit/comment.py

This improves typing in a couple spots.

Typing improvments

---

CHANGES.rst
docs/code_overview/other.rst
docs/code_overview/other/token_manager.rst
docs/examples/lmgtfy_bot.py
docs/examples/obtain_refresh_token.py
docs/examples/use_file_token_manager.py
docs/getting_started/authentication.rst
docs/getting_started/configuration/options.rst
docs/tutorials/refresh_token.rst
praw/config.py
praw/models/auth.py
praw/reddit.py
praw/util/token_manager.py
setup.py
tests/conftest.py
tests/integration/__init__.py
tests/unit/test_deprecations.py
tests/unit/test_reddit.py
tests/unit/util/test_token_manager.py

When complete, this PR will resolve #1630.
The documentation is built for this branch and can be found here: https://praw.readthedocs.io/en/callbacks/index.html

Support single-use refresh tokens

---

tests/conftest.py
tests/integration/models/reddit/test_widgets.py

Just removes some things left over from when PRAW supported Python 2.

Remove Python 2 remnants

---

CHANGES.rst
praw/models/reddit/subreddit.py

Add deprecation warning for legacy modmail

---

.github/workflows/ci.yml
pre_push.py

Fix docstrfmt exclude parameter

---

CHANGES.rst
docs/code_overview/other.rst
docs/code_overview/other/usersubreddit.rst
docs/code_overview/other/usersubredditmoderation.rst
praw/models/__init__.py
praw/models/reddit/redditor.py
praw/models/reddit/subreddit.py
praw/models/reddit/user_subreddit.py
tests/integration/cassettes/TestUserSubreddit.test_update.json
tests/integration/models/reddit/test_user_subreddit.py
tests/unit/test_deprecations.py

Fixes #1555
This objectifies the `subreddit` attribute in the Redditor class.
* #1556

Objectify user subreddit

---

.github/workflows/stale-action.yml

Add GitHub Actions workflow for handling stale issues and pull requests

---

.github/workflows/stale-action.yml

Finalize workflow

---

CHANGES.rst
praw/models/reddit/redditor.py
tests/integration/cassettes/TestRedditor.test_block.json
tests/integration/models/reddit/test_redditor.py

You can use names instead of fullnames when you block someone. This saves an API call if the blocked user's information hasn't been fetched.
Note: this method also works if you use `data={"name": self.name}` instead of `params={"name": self.name}`.
* https://www.reddit.com/dev/api#POST_api_block_user

Modify Redditor.block

---

setup.py

This will enable us to merge code which depends on the `TooManyRequests`
exception.

Depend on at least prawcore 2.1

---

.github/workflows/set_active_versions.yml
tools/set_active_docs.py

This is to set which versions are visible on readthedocs based on the latest version.

Add set_active_docs.py to set what versions are visible

---

praw/models/reddit/user_subreddit.py

This removes an unnecessary note and fixes a tiny punctuation error.

Remove unnecessary note in UserSubreddit docstring

---

AUTHORS.rst
docs/getting_started/quick_start.rst

Removed passive aggressive tone from quick start guide. That's it, that's the PR

Removed passive aggressive tone from quick start guide

---

tools/set_active_docs.py

This fixes a bug where it would hide the current version because it was pulling the latest dev version of the repo.

Fix set_active_docs.py

---

CHANGES.rst
docs/code_overview/other.rst
praw/endpoints.py
praw/models/reddit/wikipage.py
tests/integration/cassettes/TestWikiPage.test_discussions.json
tests/integration/cassettes/TestWikiPageModeration.test_revert.json
tests/integration/cassettes/TestWikiPageModeration.test_revert_css_fail.json
tests/integration/models/reddit/test_wikipage.py

Add :meth:`.WikiPage.discussions` and :meth:`.WikiPageModeration.revert`.
* https://www.reddit.com/dev/api#GET_wiki_discussions_{page}
* https://www.reddit.com/dev/api#POST_api_wiki_revert

Add WikiPage.discussions and WikiPageModeration.revert

---

docs/conf.py
setup.py

Fixes bullets not showing up in some places in the docs.
* https://github.com/praw-dev/praw/pull/1753#issuecomment-873504861

Fix bullets on readthedocs

---

CHANGES.rst
docs/getting_started/authentication.rst
docs/tutorials/refresh_token.rst
praw/config.py
praw/models/auth.py
praw/reddit.py
praw/util/token_manager.py
tests/conftest.py
tests/integration/__init__.py
tests/unit/test_deprecations.py
tests/unit/test_reddit.py

- https://www.reddit.com/r/redditdev/comments/olk5e6/followup_oauth2_api_changes_regarding_refresh/

Deprecate refresh token managers

---

AUTHORS.rst
praw/models/reddit/comment.py

Typo Fix in the Docs

---

AUTHORS.rst
docs/getting_started/authentication.rst
docs/tutorials/refresh_token.rst

Doco - cut-past the note on praw.ini usage to authentication.rst
First time AUTHORS.rst
Upon first using praw, I had a few points of confusion that are hopefully clarified by these doc updates

Doco - describe refresh_token process

---

praw/models/reddit/subreddit.py

Fixes #1781 
Fixes code example typo.

Fix code example typo

---

.github/workflows/pre-commit_autoupdate.yml

Fixes pre-commit hook auto update workflow.
- https://github.com/praw-dev/praw/pull/1784#issuecomment-919659025

Fix pre-commit hook auto update workflow

---

docs/getting_started/configuration/prawini.rst

Discussion here: https://old.reddit.com/r/redditdev/comments/q0y3nm/stuck_on_401_http_error/hfdm2xp/?context=3

Clarify that example sensitive values aren't valid

---

CHANGES.rst
docs/code_overview/models/draft.rst
docs/code_overview/other.rst
docs/code_overview/other/draftlist.rst
docs/code_overview/other/usersubreddit.rst
docs/code_overview/praw_models.rst
docs/code_overview/reddit/drafts.rst
docs/code_overview/reddit_instance.rst
praw/endpoints.py
praw/models/__init__.py
praw/models/helpers.py
praw/models/list/draft.py
praw/models/reddit/draft.py
praw/models/reddit/subreddit.py
praw/objector.py
praw/reddit.py
tests/integration/cassettes/TestDraft.test_create.json
tests/integration/cassettes/TestDraft.test_delete.json
tests/integration/cassettes/TestDraft.test_fetch.json
tests/integration/cassettes/TestDraft.test_list.json
tests/integration/cassettes/TestDraft.test_submit.json
tests/integration/cassettes/TestDraft.test_submit__different_subreddit.json
tests/integration/cassettes/TestDraft.test_submit__different_title.json
tests/integration/cassettes/TestDraft.test_update.json
tests/integration/models/reddit/test_draft.py
tests/unit/models/reddit/test_draft.py

This adds support for drafts on new reddit.

Add support for drafts

---

CHANGES.rst
praw/models/helpers.py
praw/models/reddit/draft.py
tests/integration/cassettes/TestDraft.test_submit__different_title.json
tests/integration/models/reddit/test_draft.py

This fixes a bug with editing draft attributes when submitting a draft and also cleans up some things with the drafts documentation.

Fix drafts

---

tests/integration/cassettes/TestUser.test_pin__num.json
tests/integration/cassettes/TestUser.test_pin__remove.json
tests/integration/models/test_user.py

This fixes and improves a couple of tests for pinning posts to profiles.

Fix and improve a couple profile pin tests

---

AUTHORS.rst
CHANGES.rst
praw/endpoints.py
praw/models/reddit/collections.py
tests/integration/cassettes/TestCollectionModeration.test_update_display_layout__empty_string.json
tests/integration/cassettes/TestCollectionModeration.test_update_display_layout__gallery.json
tests/integration/cassettes/TestCollectionModeration.test_update_display_layout__invalid_layout.json
tests/integration/cassettes/TestCollectionModeration.test_update_display_layout__lowercase.json
tests/integration/cassettes/TestCollectionModeration.test_update_display_layout__none.json
tests/integration/cassettes/TestCollectionModeration.test_update_display_layout__timeline.json
tests/integration/models/reddit/test_collections.py

Currently, there is no PRAW function to modify a collection's display layout to either:
* `TIMELINE`: Best for event or discussion collections
* `GALLERY`: Best for image-heavy or meme collections 
This feature allows the user to do just that. 
A solution to this problem.
* An additional PRAW function will need to be made that sets a display layout type when creating a new collection.
* Sorry about the duplicate commit message. The second one should have said "Forgot to include unit test".

Collection layout

---

CHANGES.rst
README.rst
docs/getting_started/quick_start.rst
docs/package_info/contributing.rst
docs/package_info/praw7_migration.rst
docs/tutorials/comments.rst
praw/models/helpers.py
praw/models/inbox.py
praw/models/listing/generator.py
praw/models/listing/mixins/subreddit.py
praw/models/reddit/collections.py
praw/models/reddit/comment.py
praw/models/reddit/emoji.py
praw/models/reddit/live.py
praw/models/reddit/modmail.py
praw/models/reddit/removal_reasons.py
praw/models/reddit/rules.py
praw/models/reddit/subreddit.py
praw/models/reddit/user_subreddit.py
praw/models/reddit/widgets.py
praw/models/reddit/wikipage.py
praw/models/util.py
praw/reddit.py
pre_push.py

This catches some things missed in the previous cleanup pr.
- #1821

More doc cleanup

---

praw/models/reddit/widgets.py

Add typing annotations to widgets.py

---

praw/models/reddit/mixins/__init__.py

Add typing annotations to reddit/models/mixins/__init__.py

---

CHANGES.rst
praw/models/reddit/collections.py
tests/integration/cassettes/TestSubredditCollectionsModeration.test_create__empty_layout.json
tests/integration/cassettes/TestSubredditCollectionsModeration.test_create__gallery_layout.json
tests/integration/cassettes/TestSubredditCollectionsModeration.test_create__invalid_layout.json
tests/integration/cassettes/TestSubredditCollectionsModeration.test_create__lowercase_layout.json
tests/integration/cassettes/TestSubredditCollectionsModeration.test_create__none_layout.json
tests/integration/cassettes/TestSubredditCollectionsModeration.test_create__timeline_layout.json
tests/integration/models/reddit/test_collections.py

Currently, there is no field to specify a collection display layout ("TIMELINE" or "GALLERY") when making a new collection. This feature builds upon PR #1829 and solves this problem.
- https://github.com/praw-dev/praw/pull/1829
- https://github.com/praw-dev/praw/pull/1830

Add support for specifying layout upon create collection

---

docs/tutorials/refresh_token.rst

This pull request fixes a typo.

Fix &amp; error

---

AUTHORS.rst
CHANGES.rst
praw/models/inbox.py
praw/models/reddit/message.py
tests/integration/cassettes/TestMessage.test_parent.json
tests/integration/cassettes/TestMessage.test_parent__from_inbox_listing.json
tests/integration/models/reddit/test_message.py

Fixes #1846 - Add a parent() method to the Message class.
This pull request adds a parent() method to the Message class.
I chose to raise an Exception where the message is already the topmost message.
After attempting several alternatives I also chose to re-use the `self._reddit.inbox.message(message_id=)` call because that function contained known logic around looping to discover the message from the listing that the Reddit API returns. Although I'd be comfortable to duplicate that logic into this method if preferred.

Issue #1846 - Add a parent() method to the Message class.

---

tests/integration/models/reddit/test_subreddit.py

Fix encoding in test

---

praw/models/listing/mixins/redditor.py
praw/models/reddit/live.py
praw/models/reddit/mixins/gildable.py
praw/models/reddit/mixins/replyable.py

Fixes #1853
This adds typing for some mixin methods and improves docs.

Add missing typing annotations and improve docs

---

praw/reddit.py

Add int to **config_settings type annotation

---

.github/CONTRIBUTING.rst
docs/package_info/contributing.rst

This adds more info for getting started with contributing to PRAW

Improve contributing docs

---

AUTHORS.rst
praw/models/reddit/subreddit.py

As discussed over on https://www.reddit.com/r/redditdev/comments/w6des4/received_403_http_response_on/ my PR contains more information about the moderator call requirements and targeted harassment prevention.

Added targetted harassment prevention note

---

docs/_static/theme_override.css

Fixes #1885
This adds some fixes and improvements to the dark mode theme.

Dark mode CSS improvements

---

docs/tutorials/reply_bot.rst

Fixes #1900 
Fixes the code blocks in the LMGTFY bot example.

Fix code blocks in LMGTFY bot example

---

CHANGES.rst
praw/const.py

Revert "Release v7.6.1"

---

.github/workflows/ci.yml
setup.py

This pull request adds support for Python 3.11

Add support for Python 3.11

---

praw/models/reddit/subreddit.py

Fixes #1925 
Fixes a typo in the muted doc example.

Fix docs for muted

---

MANIFEST.in
setup.py

Add py.typed stub

---

CHANGES.rst
praw/const.py

Revert "Release v7.7.0"

---

.github/workflows/codeql.yml
README.rst
setup.py

Add CodeQL

---

CHANGES.rst
praw/models/reddit/modmail.py
tests/integration/cassettes/TestModmailConversation.test_reply__internal.json
tests/integration/models/reddit/test_modmail.py

Fix modmail reply bug

---

tests/integration/models/reddit/test_widgets.py

Fix flake8 complaint

---

CHANGES.rst
README.rst
docs/getting_started/installation.rst
docs/getting_started/quick_start.rst
pyproject.toml
tox.ini

Drop support for Python 3.7

---

CHANGES.rst
praw/models/reddit/redditor.py
praw/reddit.py
tests/integration/cassettes/TestComment.test_resolve_from_share_url.json
tests/integration/cassettes/TestComment.test_resolve_from_share_url__invalid_url.json
tests/integration/cassettes/TestSubmission.test_resolve_from_share_url.json
tests/integration/cassettes/TestSubmission.test_resolve_from_share_url__invalid_url.json
tests/integration/models/reddit/test_comment.py
tests/integration/models/reddit/test_submission.py

Fixes #1968
This pull request add support for the new share link format created by mobile apps (e.g., https://www.reddit.com/r/redditdev/s/nGnQE1QkLC).

Add support for new share link
